 'use client';
import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { parseReviewToken, reviewOccasions } from '@/lib/review-validation';
export default function ReviewForm(){
 const [token,setToken]=useState('');const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);
 useEffect(()=>{const value=window.location.hash.slice(1);setToken(parseReviewToken(value)?value:'');setReady(true);},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const fields=new FormData(event.currentTarget);try{const response=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,name:fields.get('name'),message:fields.get('message'),occasion:fields.get('occasion'),rating:Number(fields.get('rating')),consent:fields.get('consent')==='on'})});const result=await response.json();if(!response.ok)throw new Error(result.error);setDone(true);window.history.replaceState(null,'','/review');}catch(error){setError(error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}}
 if(!ready)return <p className="public-copy">Opening your invitation…</p>;
 if(done)return <div role="status" className="public-review-confirmation"><h2>Thank you.</h2><p>Your review has been sent to the studio and will appear on our website once it has been checked.</p><Link className="public-text-link" href="/#reviews">See client reviews →</Link></div>;
 if(!token)return <p className="public-copy">Please open the personal review link sent by the studio. Need a link? <Link href="/contact">Get in touch</Link>.</p>;
 return <form className="bp-enquiry-form" onSubmit={submit}><fieldset className="enquiry-fields" disabled={busy}><div className="bp-field bp-field-wide"><label htmlFor="review-name">Name to display publicly</label><input id="review-name" name="name" required maxLength={80} placeholder="For example, first names only"/><small>Use the name you’re comfortable showing on our website.</small></div><div className="bp-field"><label htmlFor="review-rating">Your rating</label><select id="review-rating" name="rating" required defaultValue=""><option value="" disabled>Choose a rating</option>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} {n===1?'star':'stars'}</option>)}</select></div><div className="bp-field"><label htmlFor="review-occasion">Your occasion</label><select id="review-occasion" name="occasion">{reviewOccasions.map(value=><option key={value}>{value}</option>)}</select></div><div className="bp-field bp-field-wide"><label htmlFor="review-message">Your review</label><textarea id="review-message" name="message" required minLength={10} maxLength={2000} placeholder="Tell us about your experience…"/><small>Please leave out private contact details.</small></div><label className="public-review-consent bp-field-wide"><input type="checkbox" name="consent" required/><span>I agree to my chosen display name, rating, occasion and review being published on the Bramble &amp; Petal website immediately. I can contact the studio to request removal.</span></label><div className="bp-field-wide"><button type="submit">{busy?'Publishing…':'Publish my review'}</button><p className="public-review-notice">Please check your review before publishing. This invitation can be used once.</p></div></fieldset>{error&&<p role="alert" className="landing-enquiry-status error">{error}</p>}</form>;
}
