 'use client';
import { useEffect, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import Link from 'next/link';
import { parseReviewToken, REVIEW_PHOTO_LIMIT, REVIEW_PHOTO_MAX_BYTES, reviewOccasions } from '@/lib/review-validation';
import { preparePhoto } from './prepare-photo';
type Photo={blob:Blob;preview:string};
export default function ReviewForm(){
 const [token,setToken]=useState('');const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);
 const [photos,setPhotos]=useState<Photo[]>([]),[preparing,setPreparing]=useState(false),previews=useRef<string[]>([]);
 useEffect(()=>{const value=window.location.hash.slice(1);setToken(parseReviewToken(value)?value:'');setReady(true);},[]);
 useEffect(()=>()=>previews.current.forEach(url=>URL.revokeObjectURL(url)),[]);
 async function addPhotos(event:ChangeEvent<HTMLInputElement>){
  const input=event.currentTarget,files=[...(input.files??[])],room=REVIEW_PHOTO_LIMIT-photos.length;input.value='';if(!files.length)return;
  setError(files.length>room?`You can add up to ${REVIEW_PHOTO_LIMIT} photos, so only the first ${room===1?'one was':`${room} were`} added.`:'');setPreparing(true);
  try{for(const file of files.slice(0,room)){const blob=await preparePhoto(file,REVIEW_PHOTO_MAX_BYTES),preview=URL.createObjectURL(blob);previews.current.push(preview);setPhotos(current=>[...current,{blob,preview}]);}}
  catch(error){setError(error instanceof Error?error.message:'Please try a different photo.');}
  finally{setPreparing(false);}
 }
 function removePhoto(index:number){URL.revokeObjectURL(photos[index].preview);setPhotos(photos.filter((_,other)=>other!==index));}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const fields=new FormData(event.currentTarget),body=new FormData();body.set('token',token);for(const key of ['name','message','occasion','rating'])body.set(key,String(fields.get(key)??''));body.set('consent',fields.get('consent')==='on'?'true':'false');photos.forEach((photo,index)=>body.append('photo',photo.blob,`photo-${index+1}.jpg`));try{const response=await fetch('/api/reviews',{method:'POST',body});const result=await response.json().catch(()=>({error:'Your review could not be sent. Please try again.'}));if(!response.ok)throw new Error(result.error);setDone(true);window.history.replaceState(null,'','/review');}catch(error){setError(error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}}
 if(!ready)return <p className="public-copy">Opening your invitation…</p>;
 if(done)return <div role="status" className="public-review-confirmation"><h2>Thank you.</h2><p>Your review has been sent to the studio and will appear on our website once it has been checked.</p><Link className="public-text-link" href="/#reviews">See client reviews →</Link></div>;
 if(!token)return <p className="public-copy">Please open the personal review link sent by the studio. Need a link? <Link href="/contact">Get in touch</Link>.</p>;
 return <form className="bp-enquiry-form" onSubmit={submit}><fieldset className="enquiry-fields" disabled={busy}><div className="bp-field bp-field-wide"><label htmlFor="review-name">Name to display publicly</label><input id="review-name" name="name" required maxLength={80} placeholder="For example, first names only"/><small>Use the name you’re comfortable showing on our website.</small></div><div className="bp-field"><label htmlFor="review-rating">Your rating</label><select id="review-rating" name="rating" required defaultValue=""><option value="" disabled>Choose a rating</option>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} {n===1?'star':'stars'}</option>)}</select></div><div className="bp-field"><label htmlFor="review-occasion">Your occasion</label><select id="review-occasion" name="occasion">{reviewOccasions.map(value=><option key={value}>{value}</option>)}</select></div><div className="bp-field bp-field-wide"><label htmlFor="review-message">Your review</label><textarea id="review-message" name="message" required minLength={10} maxLength={2000} placeholder="Tell us about your experience…"/><small>Please leave out private contact details.</small></div>
  <div className="bp-field bp-field-wide public-review-photo-field"><p className="public-review-photo-title">Photos <small>Optional · up to {REVIEW_PHOTO_LIMIT}</small></p>{photos.length>0&&<ul className="public-review-photo-picks">{photos.map((photo,index)=><li key={photo.preview}><img src={photo.preview} alt={`Your photo ${index+1}`}/><button type="button" onClick={()=>removePhoto(index)} aria-label={`Remove photo ${index+1}`}>×</button></li>)}</ul>}{photos.length<REVIEW_PHOTO_LIMIT&&<><input id="review-photos" className="public-review-photo-input" type="file" accept="image/*" multiple disabled={preparing} onChange={addPhotos}/><label htmlFor="review-photos" className="public-review-photo-add">{preparing?'Preparing photos…':photos.length?'Add another photo':'Add photos'}</label></>}<small>Please only add photos you’re happy for us to show. Location details are removed before sending.</small></div>
  <label className="public-review-consent bp-field-wide"><input type="checkbox" name="consent" required/><span>I agree to my chosen display name, rating, occasion, review and any photos I add being published on the Bramble &amp; Petal website. I can contact the studio to request removal.</span></label><div className="bp-field-wide"><button type="submit" disabled={preparing}>{busy?'Publishing…':'Publish my review'}</button><p className="public-review-notice">Please check your review before publishing. This invitation can be used once.</p></div></fieldset>{error&&<p role="alert" className="landing-enquiry-status error">{error}</p>}</form>;
}
