'use client';
import { useState } from 'react';
import { studioInsights } from '@/lib/studio-insights';
import { businessIntelligence } from '@/lib/business-intelligence';
import { actionItems, addDays, day } from '@/lib/operations-model';
import { money } from '@/lib/pricing';
import type { StudioData } from '@/lib/types';
import { Heading, type SaveData, type OpenRecord } from './ops-ui';
export default function BusinessDashboard({ data, save, open }: { data: StudioData; save: SaveData; open: OpenRecord }) {
  const [from, setFrom] = useState(''); const [to, setTo] = useState(day());
  const report = businessIntelligence(data, from, to); const actions = actionItems(data);
  const ranking = (title: string, rows: { name: string; profit: number }[]) => <section className="ops-panel"><h2>{title}</h2>{rows.length ? rows.slice(0, 5).map((r, i) => <div className="ops-rank" key={`${r.name}-${i}`}><span>{r.name}</span><b className={r.profit < 0 ? 'ops-loss' : ''}>{money(r.profit)}</b></div>) : <p>Purchased work will appear here.</p>}</section>;
  const max = Math.max(1, ...report.monthly.map(m => Math.abs(m.profit)));
  return <div className="ops-dashboard"><Heading eyebrow="YOUR BUSINESS, CLEARLY" title="Business overview"><p>Profit, outstanding work and the next useful action.</p></Heading><div className="ops-toolbar"><label>From<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>To<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><button type="button" onClick={() => { setFrom(''); setTo(day()); }}>All time</button><button type="button" onClick={() => open('calculator')}>+ Recipe Builder</button><button type="button" onClick={() => open('leads')}>+ Enquiry / event</button></div>
    <div className="ops-kpis">{[['Revenue · ex VAT', report.revenue], ['Gross profit · before logged waste', report.gross], ['Logged wastage · cost', report.waste], ['Estimated net profit · after waste & tax', report.net], ['VAT charged · before input VAT', report.vat], ['Estimated corporation tax', report.tax], ['Projected cash remaining', report.net], ['Payments recorded · inc VAT', report.paid]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong className={Number(value) < 0 ? 'ops-loss' : ''}>{money(Number(value))}</strong></article>)}<article><span>Average gross margin · revenue weighted</span><strong>{report.margin}%</strong></article></div>
    <p className="ops-finance-note">Purchased work only, dated by purchase. Combined quotations replace their individual recipe revenue. Projected cash assumes full payment and all costs paid; payments recorded are a separate measure. Tax uses {data.settings.corporationTaxRate ?? 25}% of positive profit after logged waste. VAT charged is not the final VAT owed: input VAT and tax adjustments are not recorded here.</p>
    <div className="ops-two-col"><section className="ops-panel"><h2>Monthly gross profit trend</h2>{report.monthly.length ? <div className="ops-chart" role="img" aria-label="Monthly gross profit; exact values listed beside each bar">{report.monthly.map(m => <div key={m.name}><span>{m.name}</span><div><i className={m.profit < 0 ? 'negative' : ''} style={{ width: `${Math.max(1, Math.abs(m.profit) / max * 100)}%` }} /></div><b>{money(m.profit)}</b></div>)}</div> : <p>Your first purchased order starts this chart.</p>}</section><section className="ops-panel"><h2>Action centre</h2>{actions.length ? actions.slice(0, 8).map(a => <div className="ops-action" key={a.id}><button type="button" onClick={() => open(a.tab, a.recordId)}><b>{a.title}</b><small>{a.detail}</small></button><button type="button" aria-label={`Snooze ${a.title} for one day`} onClick={() => void save({ ...data, operations: { ...data.operations!, dismissedActions: [...(data.operations?.dismissedActions || []).filter(d => d.id !== a.id), { id: a.id, until: addDays(day(), 1) }] } }, 'Action snoozed.')}>Tomorrow</button></div>) : <p>You’re up to date. New follow-ups, shortages and payment reminders will appear here.</p>}</section>
    {ranking('Most profitable products / designs', report.products)}{ranking('Most profitable weddings', report.weddings)}{ranking('Lowest margin jobs', report.lowest)}{ranking('Best customers · gross profit', report.customers)}{ranking('Product categories · gross profit', report.categories)}{ranking('Best suppliers · estimated flower contribution', studioInsights(data, from, to).suppliers)}<section className="ops-panel"><h2>Supplier performance</h2><p>Compare stock usage, attributed flower profit and wastage by supplier in Flower &amp; waste insights. Allocation is an estimate for mixed designs.</p><button type="button" onClick={() => open('insights')}>View flower &amp; supplier insights</button></section></div></div>;
}
