'use client';
import { useState } from 'react';
import type { Customer, StudioData } from '@/lib/types';
import { emptyOperations, type CRMEntry } from '@/lib/operations-types';
import { financialOrders, newId, day } from '@/lib/operations-model';
import { money } from '@/lib/pricing';
import { Fields, Assets, type SaveData } from './ops-ui';
export default function CustomerTimeline({ data, customer, save }: { data: StudioData; customer: Customer; save: SaveData }) {
  const [profile, setProfile] = useState(customer); const [entry, setEntry] = useState<CRMEntry>({ id: newId(), customerId: customer.id, kind: 'Note', text: '', date: day(), dueDate: '', completed: false, assets: [] }); const [busy, setBusy] = useState(false);
  const ops = { ...emptyOperations(), ...data.operations }; const orders = financialOrders(data).filter(o => o.purchased && o.clientName.trim().toLowerCase() === customer.name.trim().toLowerCase());
  return <section className="ops-panel"><h2>Client relationship & profitability</h2><div className="ops-profit-cards"><div><span>Lifetime gross profit</span><strong>{money(orders.reduce((s, o) => s + o.profit, 0))}</strong></div><div><span>Outstanding balance</span><strong>{money(orders.reduce((s, o) => s + o.balance, 0))}</strong></div></div><details><summary>Preferences & important dates</summary><Fields value={profile} onChange={setProfile} fields={[{ key: 'contact', label: 'Contact' }, { key: 'preferredFlowers', label: 'Preferred flowers' }, { key: 'preferredColours', label: 'Preferred colours' }, { key: 'anniversary', label: 'Anniversary', type: 'date' }, { key: 'importantDates', label: 'Other important dates' }, { key: 'notes', label: 'Internal client notes', type: 'textarea' }]} /><button type="button" disabled={busy} onClick={async () => { setBusy(true); try { await save({ ...data, customers: data.customers.map(c => c.id === customer.id ? { ...c, ...profile } : c) }, 'Client preferences saved.'); } finally { setBusy(false); } }}>Save preferences</button></details><h3>Notes, messages & follow-ups</h3><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { if (await save({ ...data, operations: { ...ops, crm: [entry, ...ops.crm] } }, 'Client history updated.')) setEntry({ ...entry, id: newId(), text: '', assets: [] }); } finally { setBusy(false); } }}><Fields value={entry} onChange={setEntry} fields={[{ key: 'kind', label: 'Entry type', options: ['Note', 'Message', 'Consultation', 'Document', 'Follow-up'] }, { key: 'date', label: 'Date', type: 'date' }, { key: 'dueDate', label: 'Follow-up due', type: 'date' }, { key: 'text', label: 'Internal note / message record', type: 'textarea' }]} /><Assets value={entry.assets} onChange={assets => setEntry({ ...entry, assets })} /><button className="button" disabled={busy || !entry.text.trim()} type="submit">Save history entry</button><p>Message entries record a conversation; they do not send a message.</p></form>{ops.crm.filter(c => c.customerId === customer.id).sort((a,b) => b.date.localeCompare(a.date)).map(c => <article className="ops-row" key={c.id}><b>{c.kind} · {c.date}</b><p>{c.text}</p>{c.assets.map(a => <p key={a.id}><a href={a.url} target="_blank" rel="noreferrer">{a.name}</a></p>)}{c.dueDate && <label className="ops-check"><input type="checkbox" checked={c.completed} onChange={() => void save({ ...data, operations: { ...ops, crm: ops.crm.map(row => row.id === c.id ? { ...row, completed: !row.completed } : row) } }, 'Follow-up updated.')} />Follow up by {c.dueDate}</label>}</article>)}</section>;
}
