'use client';
import { useEffect, useRef } from 'react';
import { money } from '@/lib/pricing';
import { Photo } from './ops-ui';
import type { clientEvent, clientQuotation } from '@/lib/client-portal';

// This component accepts only the client allowlists, never a complete StudioData record.
export default function EventPresentation({ plan, quotes, close }: { plan: ReturnType<typeof clientEvent>; quotes: ReturnType<typeof clientQuotation>[]; close: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; const trigger = document.activeElement as HTMLElement | null; const overflow = document.body.style.overflow; dialog?.showModal(); document.body.style.overflow = 'hidden'; return () => { dialog?.close(); document.body.style.overflow = overflow; trigger?.focus(); }; }, []);
  const from = plan.inspiration.reduce((n,i) => n+i.priceFrom*i.quantity,0), to = plan.inspiration.reduce((n,i) => n+i.priceTo*i.quantity,0);
  return <dialog ref={ref} className="studio-presentation" aria-label="Client presentation" onCancel={e => e.preventDefault()}><div className="studio-presentation-inner"><header><span>BRAMBLE &amp; PETAL · YOUR FLORAL STORY</span><button type="button" className="ops-no-print" onClick={close}>Return to private Studio</button></header><div className="studio-presentation-title"><p>{plan.type === 'Funeral' ? 'A thoughtful tribute' : 'Flowers for your day'}</p><h1>{plan.clientName || 'Your floral plan'}</h1><p>{plan.eventDate || 'Date to be confirmed'}{plan.venue && ` · ${plan.venue}`}</p><p>{plan.palette}</p></div>
    {!!plan.references.length && <section><h2>Your mood board</h2><div className="studio-mood-board">{plan.references.map(r => <figure key={r.id}><Photo src={r.dataUrl} alt={r.caption || 'Floral inspiration'} />{r.caption && <figcaption>{r.caption}</figcaption>}</figure>)}</div></section>}
    <section><h2>Your flowers</h2>{plan.inspiration.length ? <div className="ops-visual-grid">{plan.inspiration.map(i => <article key={i.id}><Photo src={i.image} alt={i.name} /><h3>{i.name}</h3><p>{i.quantity} required · {i.description}</p><p>{i.notes}</p><strong>{money(i.quantity*i.priceFrom)}–{money(i.quantity*i.priceTo)}</strong><small>Guide price</small></article>)}</div> : <p>{plan.arrangements || 'We’ll gather your ideas here as the plan takes shape.'}</p>}{!!plan.requirements.length && <div className="studio-arrangement-list">{plan.requirements.map(r => <p key={r.id}><b>{r.quantity} × {r.name}</b>{r.notes && ` · ${r.notes}`}</p>)}</div>}{plan.inspiration.length ? <div className="studio-presentation-estimate"><span>Estimated floral total</span><strong>{money(from)}–{money(to)}</strong><p>A guide while we explore your ideas. Your formal quote will confirm the final price.</p></div> : plan.finishedEstimate !== null ? <div className="studio-presentation-estimate"><span>Estimated floral total</span><strong>{money(plan.finishedEstimate)}</strong></div> : null}</section>
    {!!plan.setupOptions.length && <section><h2>Options for your setting</h2><div className="ops-visual-grid">{plan.setupOptions.map(o => <article key={o.id}><Photo src={o.photoSrc} alt={o.title} /><h3>{o.title}</h3><p>{o.description}</p><p>{o.quantity} required{o.unitPrice !== null && ` · ${money(o.quantity*o.unitPrice)}`}</p>{o.selected && <span>Selected for your plan</span>}</article>)}</div></section>}
    {quotes.map(q => <section className="studio-presentation-quote" key={q.id}><h2>{q.name}</h2>{q.recipes.map(r => <p key={r.id}><span>{r.quantity} × {r.name}</span><strong>{money(r.total)}</strong></p>)}<div className="studio-presentation-estimate"><span>Your complete quote</span><strong>{money(q.total)}</strong></div><p>{q.approval?.status || 'Awaiting your response'}</p>{q.approval?.comments && <p>{q.approval.comments}</p>}{q.terms && <details><summary>Your arrangements & terms</summary><p className="ops-prewrap">{q.terms}</p></details>}<p>Your private invitation lets you approve the quote or request changes.</p></section>)}
    <footer>Thoughtful flowers, made with feeling.</footer></div></dialog>;
}
