'use client';
import { useState } from 'react';
import ProfitabilityPanel from './profitability-panel';
import { eventProfitInput } from '@/lib/profitability';
import Dialog from '../dialog';
import { newId, financialOrders } from '@/lib/operations-model';
import { eventQuoteTotals, recipeRequirements } from '@/lib/studio-commands';
import { money, calculateTotals } from '@/lib/pricing';
import type { StudioData, WeddingPlan } from '@/lib/types';
import type { EventQuote } from '@/lib/operations-types';
import { Fields, Status, type RunCommand } from './ops-ui';
export function QuotePresentation({ quote, data }: { quote: EventQuote; data: StudioData }) {
  const order = financialOrders(data).find(o => o.id === quote.id);
  return <div className="ops-client-document"><p className="eyebrow">BRAMBLE &amp; PETAL · FLORIST STUDIO</p><h1>{quote.name}</h1><p>Prepared for {quote.clientName}</p><Status>{quote.invoicedAt ? 'Invoice' : 'Formal quotation'} · {quote.id.slice(0, 8).toUpperCase()}</Status><div className="ops-client-quote-lines">{quote.recipes.map(r => <div key={r.id}><span>{r.quantity} × {r.name}</span><b>{money(r.total)}</b></div>)}{[['Setup', quote.setup], ['Delivery', quote.delivery], ['Hire', quote.hire || 0], ['Discount', -quote.discount]].filter(([, n]) => n !== 0).map(([name, n]) => <div key={String(name)}><span>{name}</span><b>{money(name === 'Discount' ? quote.total - quote.recipes.reduce((sum, r) => sum + r.total, 0) - (quote.setup + quote.delivery + (quote.hire || 0)) * (quote.vatApplies ? 1 + quote.vatRate / 100 : 1) : Number(n) * (quote.vatApplies ? 1 + quote.vatRate / 100 : 1))}</b></div>)}</div><div className="ops-total"><span>Total including applicable VAT</span><strong>{money(quote.total)}</strong></div><p>Includes {money(quote.vat)} VAT.</p>{quote.depositDue ? <p>Booking deposit: <b>{money(quote.depositDue)}</b></p> : null}{order && <p>Payments recorded: {money(order.paid)} · Balance remaining: {money(order.balance)}</p>}{quote.paymentDue && <p>Balance due: {quote.paymentDue}</p>}{quote.stages?.length ? <section><h2>Payment schedule</h2>{quote.stages.map(s => <p key={s.id}>{s.name} · {money(s.amount)} · due {s.due}</p>)}</section> : null}{quote.terms && <section><h2>Terms &amp; arrangements</h2><p className="ops-prewrap">{quote.terms}</p></section>}<p className="ops-muted">Please contact the studio to arrange payment. No online payment is taken on this page.</p></div>;
}
export default function EventQuotation({ data, plan, command, onDirty, confirmationOnly = false }: { confirmationOnly?: boolean; onDirty?: () => void; data: StudioData; plan: WeddingPlan; command: RunCommand }) {
  const existing = data.operations?.eventQuotes.find(q => q.planId === plan.id);
  const [draft, setDraft] = useState<EventQuote>(() => structuredClone(existing || { id: newId(), planId: plan.id, clientName: plan.clientName, name: `${plan.clientName} — ${plan.type}${plan.eventDate ? ` · ${plan.eventDate}` : ''}`, recipeIds: [], recipes: [], setup: 0, delivery: 0, hire: 0, discount: 0, vatRate: data.settings.vatRate, vatApplies: true, total: 0, vat: 0, status: 'QUOTE', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), terms: '' }));
  const [busy, setBusy] = useState(false); const [present, setPresent] = useState(false); const [confirmPurchase, setConfirmPurchase] = useState(false); const [shortages, setShortages] = useState(false); const [response, setResponse] = useState('Approved'); const [comments, setComments] = useState(''); const [terms, setTerms] = useState(false);
  const choices = data.quotes.filter(r => r.planId === plan.id && r.status !== 'DRAFT' && !r.isTemplate);
  const recipes = choices.filter(r => draft.recipeIds.includes(r.id));
  const totals = eventQuoteTotals(recipes, draft);
  const quote = existing || draft;
  const needs = new Map<string, { name: string; required: number; available: number }>();
  for (const recipe of choices.filter(r => quote.recipeIds.includes(r.id))) for (const n of recipeRequirements(recipe)) { const old = needs.get(n.inventoryId); needs.set(n.inventoryId, { name: n.name, required: (old?.required || 0) + n.quantity, available: data.inventory.find(i => i.id === n.inventoryId)?.stemsRemaining || 0 }); }
  return <section className="ops-panel" onChange={onDirty}><div className="ops-section-title"><h2>Formal event quotation</h2>{existing && <Status>{existing.status}</Status>}</div><p>Combine the event’s quoted recipes into one customer quotation. Estimates stay separate.</p>
    {!confirmationOnly && existing?.status !== 'PURCHASED' && <><label>Quotation title<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label>{choices.length ? choices.map(r => <label className="ops-check" key={r.id}><input type="checkbox" checked={draft.recipeIds.includes(r.id)} onChange={e => setDraft({ ...draft, recipeIds: e.target.checked ? [...draft.recipeIds, r.id] : draft.recipeIds.filter(id => id !== r.id) })} /><span>{r.quantity || 1} × {r.name || r.occasion} · {money(calculateTotals(r).grossTotal)}</span></label>) : <p className="ops-empty-inline">Save the event’s recipes as Quote first, then combine them here.</p>}
      <details className="studio-more-details"><summary>Delivery, setup & pricing details</summary><Fields value={draft} onChange={setDraft} fields={[{ key: 'setup', label: 'Setup charge (£, ex VAT)', type: 'number' }, { key: 'delivery', label: 'Delivery charge (£, ex VAT)', type: 'number' }, { key: 'hire', label: 'Hire charge (£, ex VAT)', type: 'number' }, { key: 'discount', label: 'Discount (£, ex VAT)', type: 'number' }, { key: 'vatRate', label: 'VAT on event extras (%)', type: 'number' }, { key: 'vatApplies', label: 'Apply VAT to event extras', type: 'checkbox' }, { key: 'setupCost', label: 'Internal setup cost (£)', type: 'number' }, { key: 'deliveryCost', label: 'Internal delivery cost (£)', type: 'number' }, { key: 'otherCost', label: 'Other internal costs (£)', type: 'number' }, { key: 'depositDue', label: 'Booking deposit (£)', type: 'number' }, { key: 'paymentDue', label: 'Balance due date', type: 'date' }, { key: 'terms', label: 'Terms shown to the client', type: 'textarea' }]} /></details>
      <details><summary>Staged payments</summary>{(draft.stages || []).map(s => <div className="ops-fields" key={s.id}><label>Stage name<input value={s.name} onChange={e => setDraft({ ...draft, stages: draft.stages?.map(p => p.id === s.id ? { ...p, name: e.target.value } : p) })} /></label><label>Amount (£)<input type="number" min="0" value={s.amount} onChange={e => setDraft({ ...draft, stages: draft.stages?.map(p => p.id === s.id ? { ...p, amount: Number(e.target.value) } : p) })} /></label><label>Due<input type="date" value={s.due} onChange={e => setDraft({ ...draft, stages: draft.stages?.map(p => p.id === s.id ? { ...p, due: e.target.value } : p) })} /></label><button type="button" onClick={() => setDraft({ ...draft, stages: draft.stages?.filter(p => p.id !== s.id) })}>Remove stage</button></div>)}<button type="button" onClick={() => setDraft({ ...draft, stages: [...(draft.stages || []), { id: newId(), name: 'Payment', amount: 0, due: '' }] })}>+ Add payment stage</button></details>
      <div className="ops-total"><span>Formal quote total</span><strong>{money(totals.total)}</strong></div><button className="button" type="button" disabled={busy || !recipes.length} onClick={async () => { setBusy(true); try { const result = await command({ type: 'saveEventQuote', quote: draft }); const saved = result?.operations?.eventQuotes.find(q => q.id === draft.id); if (saved) setDraft(saved); } finally { setBusy(false); } }}>{busy ? 'Saving…' : 'Save formal quote'}</button></>}
    {confirmationOnly && !existing && <p>Save a final quote before confirming this event.</p>}
    {!confirmationOnly && <ProfitabilityPanel title="Your quote & profit" input={eventProfitInput(data, [existing?.status === 'PURCHASED' ? existing : { ...draft, total: totals.total, vat: totals.vat }])} />}
    {existing && <div className="ops-toolbar"><button type="button" onClick={async () => { if (await command({ type: 'issueInvoice', orderId: existing.id })) setPresent(true); }}>Issue / view invoice</button><button type="button" onClick={() => setPresent(true)}>Present / print customer quote</button>{existing.status === 'QUOTE' && <button type="button" className="button" onClick={() => setConfirmPurchase(true)}>Mark as Purchased</button>}<span>{existing.approval?.status || 'Awaiting client response'}</span></div>}
    {existing?.status === 'QUOTE' && <details><summary>Record a client response received outside the portal</summary><label>Response<select value={response} onChange={e => setResponse(e.target.value)}><option>Approved</option><option>Changes requested</option></select></label><label>Client comments<textarea value={comments} onChange={e => setComments(e.target.value)} /></label><label className="ops-check"><input type="checkbox" checked={terms} onChange={e => setTerms(e.target.checked)} />The client accepted the quotation terms</label><button type="button" onClick={() => void command({ type: 'recordApproval', quoteId: existing.id, status: response as 'Approved' | 'Changes requested', comments, termsAccepted: terms })}>Record response</button></details>}
    {present && <Dialog label="Customer quotation" className="ops-document-dialog" onClose={() => setPresent(false)}><div className="ops-toolbar ops-no-print"><button type="button" onClick={() => setPresent(false)}>Close</button><button type="button" onClick={() => window.print()}>Print / save PDF</button></div><QuotePresentation data={data} quote={quote} /></Dialog>}
    {confirmPurchase && <Dialog label="Confirm event purchase" className="ops-confirm-dialog" onClose={() => !busy && setConfirmPurchase(false)}><h2>Confirm {plan.type.toLowerCase()} purchase</h2><p>{plan.clientName} · {plan.eventDate || 'Date to confirm'}</p><strong className="ops-large-price">{money(quote.total)}</strong><h3>Recipes included</h3>{quote.recipes.map(r => <p key={r.id}>{r.quantity} × {r.name}</p>)}<h3>Stock commitment</h3>{[...needs.values()].map(n => <p key={n.name}>{n.name}: {n.required} required · {n.available} available{n.required > n.available && <b> · {n.required - n.available} short</b>}</p>)}{[...needs.values()].some(n => n.required > n.available) && <label className="ops-check"><input type="checkbox" checked={shortages} onChange={e => setShortages(e.target.checked)} />Include these shortages in purchase requirements</label>}<p>Every recipe and its available stock are committed together. A failure saves none of the purchase. This does not take payment.</p><div className="ops-toolbar"><button type="button" disabled={busy} onClick={() => setConfirmPurchase(false)}>Back</button><button className="button" type="button" disabled={busy || ([...needs.values()].some(n => n.required > n.available) && !shortages)} onClick={async () => { setBusy(true); try { if (await command({ type: 'purchaseEventQuote', quoteId: quote.id, allowShortages: shortages })) setConfirmPurchase(false); } finally { setBusy(false); } }}>{busy ? 'Confirming…' : 'Confirm Purchased'}</button></div></Dialog>}
  </section>;
}
