'use client';
import { useState } from 'react';
import type { StudioData, WeddingPlan, Quote } from '@/lib/types';
import type { EventDetails, InspirationItem, InspirationSelection, EventRequirement } from '@/lib/operations-types';
import { estimateTotal, newId, newRecipe, financialOrders } from '@/lib/operations-model';
import { money } from '@/lib/pricing';
import { recipeProfitInput, eventProfitInput, type ProfitInput } from '@/lib/profitability';
import { CatalogueBrowse } from './inspiration-catalogue';
import EventQuotation from './event-quotation';
import EventPresentation from './event-presentation';
import { clientEvent, clientQuotation } from '@/lib/client-portal';
import ProfitabilityPanel from './profitability-panel';
import { Assets, Fields, Heading, Photo, Status, type SaveData, type RunCommand } from './ops-ui';

const weddingRequirements = ['Bridal bouquet', 'Bridesmaid bouquet', 'Flower girl flowers', 'Buttonholes', 'Corsages', 'Ceremony flowers', 'Aisle flowers', 'Pew / chair flowers', 'Registrar table', 'Floral arch', 'Entrance display', 'Welcome sign flowers', 'Table centrepiece', 'Top table', 'Cake flowers', 'Staircase flowers', 'Hanging installation', 'Bar flowers', 'Thank-you bouquet', 'Bespoke arrangement'];
const funeralRequirements = ['Coffin spray', 'Wreath', 'Posy', 'Sheaf', 'Letter tribute', 'Heart tribute', 'Cross', 'Bespoke tribute', 'Sympathy bouquet', 'Service flowers', 'Other arrangement'];
export function EventFields({ plan, onChange }: { plan: WeddingPlan; onChange: (p: WeddingPlan) => void }) {
  const details = plan.details || {};
  return <><Fields value={plan} onChange={onChange} fields={[{ key: 'clientName', label: plan.type === 'Wedding' ? 'Client / couple' : 'Client / family contact', required: true }, { key: 'contact', label: 'Phone / email' }, { key: 'eventDate', label: `${plan.type} date`, type: 'date' }, { key: 'venue', label: 'Venue / delivery location' }, { key: 'budget', label: 'Overall floral budget (£)', type: 'number' }, { key: 'palette', label: 'Colour palette' }, { key: 'favouriteFlowers', label: 'Flower preferences' }, { key: 'avoidFlowers', label: 'Flowers to avoid' }, { key: 'status', label: 'Planning status', options: ['Enquiry', 'Planning', 'Proposal sent', 'Booked'] }, ...(plan.type === 'Wedding' ? [{ key: 'brideHeight', label: 'Height of the bride' }, { key: 'tableCount', label: 'Number of tables', type: 'number' as const }, { key: 'mainTableSize', label: 'Top table size' }, { key: 'guestCount', label: 'Guest numbers', type: 'number' as const }] : plan.type === 'Funeral' ? [{ key: 'personRemembered', label: 'Deceased name' }, { key: 'serviceTime', label: 'Service time', type: 'time' as const }, { key: 'funeralDirector', label: 'Funeral director' }, { key: 'serviceWishes', label: 'Service wishes', type: 'textarea' as const }, { key: 'cardMessage', label: 'Card message', type: 'textarea' as const }] : [{ key: 'eventFormat', label: 'Event format' }, { key: 'guestCount', label: 'Guest numbers', type: 'number' as const }]), { key: 'arrangements', label: 'Original floral requirements', type: 'textarea' }, { key: 'notes', label: 'Shared floral brief / client notes', type: 'textarea' }]} />
    <details><summary>Venue, consultation &amp; logistics details</summary><Fields value={details} onChange={d => onChange({ ...plan, details: d })} fields={[...(plan.type === 'Wedding' ? [{ key: 'ceremonyTime', label: 'Ceremony time', type: 'time' as const }, { key: 'ceremonyVenue', label: 'Ceremony venue' }, { key: 'receptionVenue', label: 'Reception venue' }, { key: 'weddingParty', label: 'Wedding party' }, { key: 'theme', label: 'Style / theme' }] : plan.type === 'Funeral' ? [{ key: 'funeralDirectorContact', label: 'Funeral director contact' }, { key: 'deliveryDeadline', label: 'Delivery deadline', type: 'time' as const }] : []), { key: 'consultationDate', label: 'Consultation date', type: 'date' }, { key: 'consultationTime', label: 'Consultation time', type: 'time' }, { key: 'consultationNotes', label: 'Internal consultation notes', type: 'textarea' }, { key: 'inspirationLinks', label: 'Pinterest / inspiration links', type: 'textarea' }, { key: 'venueInformation', label: 'Venue information / access', type: 'textarea' }, { key: 'deliveryRequirements', label: 'Delivery requirements', type: 'textarea' }, { key: 'collectionTime', label: 'Collection time', type: 'time' }, { key: 'followUpDate', label: 'Follow-up date', type: 'date' }, { key: 'actions', label: 'Follow-up actions', type: 'textarea' }]} /><Fields value={plan} onChange={onChange} fields={[{ key: 'setupWindow', label: 'Setup time / window' }, { key: 'breakdownTime', label: 'Breakdown / collection' }, { key: 'venueRestrictions', label: 'Venue restrictions', type: 'textarea' }]} /></details></>;
}
export function ClientEventSummary({ plan }: { plan: WeddingPlan }) {
  const estimate = estimateTotal(plan);
  return <section className="ops-client-summary"><p className="eyebrow">OUR FLORAL PLAN</p><h2>{plan.clientName}</h2><p>{plan.eventDate || 'A date to look forward to'}{plan.venue ? ` · ${plan.venue}` : ''}</p><div className="ops-visual-grid">{(plan.inspiration || []).map(i => <article key={i.id}><Photo src={i.image} alt={i.name} /><h3>{i.name}{i.quantity > 1 && ` × ${i.quantity}`}</h3><p>{i.notes}</p><b>{money(i.priceFrom * i.quantity)}–{money(i.priceTo * i.quantity)}</b><small>Estimated price</small></article>)}</div>{plan.inspiration?.length ? <div className="ops-estimate-total"><span>Estimated floral budget</span><strong>{money(estimate.from)}–{money(estimate.to)}</strong></div> : <p>Your floral ideas will appear here as the plan takes shape.</p>}<p className="ops-estimate-note">This is a consultation estimate, not a formal quotation. Final prices depend on flower choice, seasonality, availability and the agreed design.</p></section>;
}
export default function EventWorkspace({ data, plan, save, command, onRecipe, onDirty }: { data: StudioData; plan: WeddingPlan; save: SaveData; command: RunCommand; onRecipe: (r: Quote) => void; onDirty: () => void }) {
  const [presentation, setPresentation] = useState(false);
  const [draft, setDraft] = useState(() => structuredClone(plan)); const [section, setSection] = useState(!plan.clientName ? 'Client' : data.operations?.eventQuotes.some(q => q.planId === plan.id && q.status === 'PURCHASED') ? 'Production' : data.operations?.eventQuotes.some(q => q.planId === plan.id) ? 'Quotation' : [...data.quotes,...data.jobs].some(r => r.planId === plan.id) ? 'Recipes' : 'Brief'); const [busy, setBusy] = useState(false); const [invitation, setInvitation] = useState(''); const [inviteId, setInviteId] = useState(''); const [notice, setNotice] = useState('');
  const [invitations, setInvitations] = useState<{id:string;created_at:string;expires_at:string;revoked_at:string|null}[]>([]);
  const [quoteDirty, setQuoteDirty] = useState(false);
  const selectSection = (next: string) => { if (next !== section && quoteDirty && !globalThis.confirm('Leave unsaved quotation changes? Cancel to save the quote first.')) return; setQuoteDirty(false); setSection(next); };
  const change = (p: WeddingPlan) => { setDraft(p); onDirty(); };
  const saveEvent = async () => {
    if (!draft.clientName.trim()) { setNotice('Add a client name.'); return false; }
    setBusy(true); try {
      const customer = data.customers.find(c => c.id === draft.customerId) || data.customers.find(c => c.name.trim().toLowerCase() === draft.clientName.trim().toLowerCase());
      const p = { ...draft, clientName: draft.clientName.trim(), customerId: customer?.id || `client-${draft.id}` };
      const customers = customer ? data.customers : [{ id: p.customerId, name: p.clientName, contact: p.contact || '', notes: '', createdAt: new Date().toISOString() }, ...data.customers];
      const ok = await save({ ...data, customers, plans: data.plans.some(p => p.id === draft.id) ? data.plans.map(row => row.id === p.id ? p : row) : [p, ...data.plans] }, `${p.type} workspace saved.`);
      if (ok) { setDraft(p); setNotice('Saved to the client’s event record.'); } return ok;
    } finally { setBusy(false); }
  };
  const select = (item: InspirationItem, quantity: number) => {
    const old = draft.inspiration?.find(i => i.inspirationId === item.id);
    change({ ...draft, inspiration: old ? draft.inspiration!.map(i => i.id === old.id ? { ...i, quantity: i.quantity + quantity } : i) : [...(draft.inspiration || []), { id: newId(), inspirationId: item.id, name: item.name, category: item.category, image: item.images[0]?.url || '', description: item.description, quantity, priceFrom: item.priceFrom, priceTo: item.priceTo, palette: item.palette, notes: '' }] }); setNotice(`${item.name} added. Save the event to keep this selection.`);
  };
  const openRecipe = async (selection?: InspirationSelection | EventRequirement) => {
    if (!await saveEvent()) return;
    const existing = [...data.quotes, ...data.jobs].find(r => r.id === selection?.recipeId);
    onRecipe(existing ? structuredClone(existing) : newRecipe(data, draft, selection));
  };
  const eventRecipes = [...data.quotes, ...data.jobs].filter(r => r.planId === plan.id);
  const profit: ProfitInput = eventRecipes.reduce((s, r) => { const p = recipeProfitInput(r, data.settings.corporationTaxRate); for (const k of Object.keys(s) as (keyof ProfitInput)[]) if (k !== 'taxRate') s[k] += p[k]; return s; }, { flower: 0, packaging: 0, sundries: 0, labour: 0, waste: 0, delivery: 0, setup: 0, collection: 0, supplier: 0, expenses: 0, selling: 0, vat: 0, taxRate: data.settings.corporationTaxRate ?? 25 });
  const formal = (data.operations?.eventQuotes || []).filter(q => q.planId === plan.id);
  if (formal.length) Object.assign(profit, eventProfitInput(data, formal));
  const steps = [{key:'Client',label:'Client'}, {key:'Brief',label:'Event Details'}, {key:'Inspiration',label:'Inspiration'}, {key:'Estimate',label:'Estimate'}, {key:'Recipes',label:'Recipe'}, {key:'Quotation',label:'Final Quote'}, {key:'Confirmed',label:'Purchased / Confirmed'}, {key:'Production',label:'Production'}];
  const stage = steps.findIndex(s => s.key === section);
  return <div className="ops-event-workspace">{presentation && <EventPresentation plan={clientEvent(draft)} quotes={formal.map(q => clientQuotation(data,q))} close={() => setPresentation(false)} />}<Heading eyebrow={`${plan.type.toUpperCase()} FLORAL PLAN`} title={draft.clientName || `New ${plan.type.toLowerCase()}`}><p>{draft.eventDate || 'Date to confirm'} · {draft.venue || 'Venue to confirm'}</p></Heading><div className="ops-toolbar ops-sticky-actions"><button className="button studio-presentation-button" type="button" onClick={() => setPresentation(true)}>Client View / Presentation Mode</button><button type="button" disabled={busy} onClick={() => void saveEvent()}>{busy ? 'Saving…' : 'Save progress'}</button></div>{notice && <p role="status" className="ops-inline-notice">{notice}</p>}
    <nav className="studio-step-flow" aria-label="Your event, step by step">{steps.map((s,i) => <button type="button" key={s.key} aria-current={section === s.key ? 'step' : undefined} onClick={() => selectSection(s.key)}><span>{i+1}</span>{s.label}</button>)}</nav>
    {stage >= 0 && <div className="studio-stage-heading"><p>STEP {stage+1} OF 8</p><h2>{steps[stage].label}</h2><p>{['Start with the person you’re creating for.', 'A few details to shape the flowers.', 'Gather colours, photographs and favourite designs.', 'A guide price to explore together.', 'Bring the design to life, stem by stem.', 'Bring your priced recipes into one clear quote.', 'Confirm the order when your client is ready. Stock is committed only when you confirm Purchased.', 'Prepare the flowers for their day.'][stage]}</p></div>}
    {section === 'Client' && <section className="ops-panel"><label>Choose an existing client<select value={draft.customerId || ''} onChange={e => { const c = data.customers.find(c => c.id === e.target.value); if (c) change({...draft,customerId:c.id,clientName:c.name,contact:c.contact}); else change({...draft,customerId:undefined,clientName:'',contact:''}); }}><option value="">New client / enter details below</option>{data.customers.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><Fields value={draft} onChange={change} fields={[{key:'clientName',label:plan.type === 'Funeral' ? 'Family contact' : 'Client / couple',required:true},{key:'contact',label:'Phone or email'}]} /></section>}
    {section === 'Brief' && <section className="ops-panel"><Fields value={draft} onChange={change} fields={[{key:'eventDate',label:plan.type === 'Funeral' ? 'Service date' : 'Event date',type:'date'},{key:'venue',label:'Venue / location'},{key:'palette',label:'Colours & style'},{key:'budget',label:'Comfortable floral budget (£)',type:'number'}]} /><details className="studio-more-details"><summary>More event details</summary><EventFields plan={draft} onChange={change} /></details><h2>Arrangement requirements</h2><div className="ops-toolbar"><label>Add a requirement<select value="" onChange={e => { if (e.target.value) change({ ...draft, requirements: [...(draft.requirements || []), { id: newId(), name: e.target.value, quantity: 1, notes: '' }] }); }}><option value="">Choose an arrangement…</option>{(plan.type === 'Funeral' ? funeralRequirements : weddingRequirements).map(r => <option key={r}>{r}</option>)}</select></label></div>{(draft.requirements || []).map(r => <div className="ops-requirement" key={r.id}><Fields value={r} onChange={next => change({ ...draft, requirements: draft.requirements?.map(i => i.id === r.id ? next : i) })} fields={[{ key: 'name', label: 'Arrangement' }, { key: 'quantity', label: 'Quantity', type: 'number' }, { key: 'notes', label: 'Design notes' }]} /><button type="button" onClick={() => void openRecipe(r)}>{r.recipeId ? 'Open recipe' : 'Create recipe'}</button><button type="button" onClick={() => change({ ...draft, requirements: draft.requirements?.filter(i => i.id !== r.id) })}>Remove requirement</button></div>)}</section>}
    {section === 'Inspiration' && <><ClientEventSummary plan={draft} />{(draft.inspiration || []).map(i => <div className="ops-selection-edit" key={i.id}><b>{i.name}</b><label>Quantity<input type="number" min="1" value={i.quantity} onChange={e => change({ ...draft, inspiration: draft.inspiration?.map(s => s.id === i.id ? { ...s, quantity: Math.max(1, Math.floor(Number(e.target.value))) } : s) })} /></label><label>Client notes<input value={i.notes} onChange={e => change({ ...draft, inspiration: draft.inspiration?.map(s => s.id === i.id ? { ...s, notes: e.target.value } : s) })} /></label><button type="button" onClick={() => void openRecipe(i)}>{i.recipeId ? 'Open recipe' : 'Create recipe'}</button><button type="button" onClick={() => change({ ...draft, inspiration: draft.inspiration?.filter(s => s.id !== i.id) })}>Remove idea</button></div>)}<h2>Explore the catalogue</h2><CatalogueBrowse items={data.operations?.catalogue || []} occasion={plan.type} onSelect={select} /></>}
    {section === 'Estimate' && <section className="ops-panel"><ClientEventSummary plan={draft} /><details><summary>Add a personal guide estimate</summary><Fields value={draft} onChange={change} fields={[{key:'finishedEstimate',label:'Estimated floral total (£)',type:'number'},{key:'arrangements',label:'Selected arrangements',type:'textarea'}]} /><p>This is a guide for the consultation. The final quote is prepared from your recipes.</p></details><button type="button" className="button" onClick={() => void openRecipe()}>Create a recipe from this plan →</button></section>}
    {section === 'Recipes' && <><button className="button" type="button" onClick={() => void openRecipe()}>+ Build Recipe</button><div className="ops-record-grid">{eventRecipes.map(r => <button type="button" className="ops-record-card" key={r.id} onClick={() => onRecipe(structuredClone(r))}><Photo src={r.inspirationImage} alt={r.name || r.occasion} /><h3>{r.name || r.occasion}</h3><p>{r.quantity || 1} required</p><Status>{r.status || ('wonAt' in r ? 'PURCHASED' : 'QUOTE')}</Status></button>)}</div>{!eventRecipes.length && <p>Choose a requirement or inspiration design to start a connected recipe.</p>}<ProfitabilityPanel input={profit} title={`${plan.type} profitability`} /></>}
    {(section === 'Quotation' || section === 'Confirmed') && <><EventQuotation key={`${plan.id}-${section}`} confirmationOnly={section === 'Confirmed'} data={data} plan={plan} command={async c => { const result = await command(c); if(result) setQuoteDirty(false); return result; }} onDirty={() => { setQuoteDirty(true); onDirty(); }} /></>}
    {section === 'Production' && <section className="ops-panel"><h2>Ready for the making table</h2>{data.jobs.filter(j => j.planId === plan.id && !j.stockReturned).map(j => <article className="studio-simple-row" key={j.id}><div><h3>{j.name || j.occasion}</h3><p>{j.quantity || 1} required</p><label>Making progress<select value={j.productionStatus || 'Not started'} onChange={e => { void command({type:'production',recipeId:j.id,status:e.target.value as NonNullable<typeof j.productionStatus>,assignedTo:j.assignedTo || '',due:j.productionDue || j.eventDate}); }}>{['Not started','Prepped','In production','Completed','Packed','Delivered'].map(status => <option key={status}>{status}</option>)}</select></label><button type="button" onClick={() => onRecipe(structuredClone(j))}>Open making instructions →</button></div></article>)}{!data.jobs.some(j => j.planId === plan.id && !j.stockReturned) && <p>Confirm your quoted recipes as Purchased first. Confirmed designs will appear here.</p>}<p>Use Business Tools → Production to assign work and update preparation, making and delivery status.</p></section>}
    {section === 'Documents' && <section className="ops-panel"><h2>Event documents &amp; inspiration board</h2><Assets value={draft.details?.documents || []} onChange={documents => change({ ...draft, details: { ...draft.details, documents } })} /><Assets imagesOnly label="Add reference photographs" value={(draft.references || []).map(r => ({ id: r.id, name: r.name, url: r.dataUrl, type: 'image/jpeg' }))} onChange={images => change({ ...draft, references: images.map(i => ({ id: i.id, name: i.name, dataUrl: i.url, caption: draft.references?.find(r => r.id === i.id)?.caption })) })} /><p>Event documents remain private to the studio. Reference photographs can be seen in the client’s floral plan.</p></section>}
    {section === 'Client view' && <><ClientEventSummary plan={draft} /><section className="ops-panel ops-no-print"><h2>Private client portal</h2><p>Create a private invitation for this event. The client can see their floral plan, browse inspiration and respond to their quote. Internal costs and notes are excluded by the server.</p><button className="button" type="button" disabled={busy} onClick={async () => { if (!await saveEvent()) return; setBusy(true); try { const r = await fetch('/api/studio/client-access', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ planId: plan.id }) }); const result = await r.json(); if (!r.ok) throw new Error(result.error); setInvitation(`${location.origin}/client#invite=${result.invite}`); setInviteId(result.id); } catch (e) { setNotice(e instanceof Error ? e.message : 'Invitation failed.'); } finally { setBusy(false); } }}>Create private invitation</button>{invitation && <div><label>Invitation link<input readOnly value={invitation} /></label><button type="button" onClick={() => void navigator.clipboard.writeText(invitation).then(() => setNotice('Invitation copied. Send it to the client when ready.'))}>Copy invitation</button><button type="button" onClick={async () => { const r = await fetch('/api/studio/client-access', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ revokeId: inviteId }) }); if (r.ok) { setInvitation(''); setNotice('Invitation revoked.'); } }}>Revoke this invitation</button></div>}<button type="button" onClick={async () => { try { const r = await fetch(`/api/studio/client-access?planId=${encodeURIComponent(plan.id)}`); const body = await r.json(); if (!r.ok) throw new Error(body.error); setInvitations(body.invitations); } catch (e) { setNotice(e instanceof Error ? e.message : 'Could not load invitations.'); } }}>Manage existing invitations</button>{invitations.map(i => <div className="ops-row" key={i.id}><p>Created {new Date(i.created_at).toLocaleDateString('en-GB')} · {i.revoked_at ? 'Revoked' : `Expires ${new Date(i.expires_at).toLocaleDateString('en-GB')}`}</p>{!i.revoked_at && <button type="button" onClick={async () => { const r = await fetch('/api/studio/client-access', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ revokeId: i.id }) }); if (r.ok) { setInvitations(rows => rows.map(row => row.id === i.id ? { ...row, revoked_at: new Date().toISOString() } : row)); setNotice('Client invitation revoked.'); } else setNotice('The invitation could not be revoked. Please try again.'); }}>Revoke invitation</button>}</div>)}<button type="button" onClick={() => window.print()}>Print floral plan</button></section></>}
    {stage >= 0 && stage < steps.length-1 && <div className="studio-next-step"><span>Next: {steps[stage+1].label}</span><button className="button" type="button" disabled={busy} onClick={async () => { if (['Client','Brief','Inspiration','Estimate'].includes(section) && !await saveEvent()) return; selectSection(steps[stage+1].key); }}>Continue to {steps[stage+1].label} →</button></div>}
    <details className="studio-event-tools"><summary>More event tools</summary><div className="ops-toolbar"><button type="button" onClick={() => selectSection('Documents')}>Documents & mood board</button><button type="button" onClick={() => selectSection('Client view')}>Private client invitations</button></div></details>
  </div>;
}
