'use client';
import { useState } from 'react';
import type { InspirationItem } from '@/lib/operations-types';
import { emptyOperations } from '@/lib/operations-types';
import type { StudioData } from '@/lib/types';
import { money } from '@/lib/pricing';
import { newId } from '@/lib/operations-model';
import { Assets, Empty, Fields, Heading, Photo, Status, type SaveData } from './ops-ui';
const styles = ['Wild', 'Garden', 'Romantic', 'Luxury', 'Modern', 'Minimal', 'Rustic', 'Boho', 'Traditional', 'Contemporary'];
const blank = (): InspirationItem => ({ id: newId(), name: '', category: 'Bridal bouquet', images: [], description: '', style: 'Garden', palette: '', season: 'Any season', occasion: 'Wedding', flowers: '', size: '', stemRange: '', priceFrom: 0, priceTo: 0, tags: '', active: true });
export function CatalogueBrowse({ items, occasion, onSelect, onEdit }: { items: InspirationItem[]; occasion?: string; onSelect?: (item: InspirationItem, quantity: number) => void; onEdit?: (item: InspirationItem) => void }) {
  const [query, setQuery] = useState(''); const [style, setStyle] = useState(''); const [colour, setColour] = useState(''); const [season, setSeason] = useState(''); const [category, setCategory] = useState(''); const [min, setMin] = useState(''); const [max, setMax] = useState(''); const [limit, setLimit] = useState(12); const [quantities, setQuantities] = useState<Record<string, number>>({});
  const filtered = items.filter(i => (!occasion || i.occasion === occasion || i.occasion === 'Other') && (onEdit || i.active) && `${i.name} ${i.flowers} ${i.tags} ${i.description}`.toLowerCase().includes(query.toLowerCase()) && (!style || i.style === style) && (!category || i.category === category) && i.palette.toLowerCase().includes(colour.toLowerCase()) && (!season || i.season === season) && (!min || i.priceTo >= Number(min)) && (!max || i.priceFrom <= Number(max)));
  return <section className="ops-catalogue"><div className="ops-filter-grid"><label>Find a design or flower<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Bouquet, rose, garden…" /></label><label>Arrangement<select value={category} onChange={e => setCategory(e.target.value)}><option value="">All arrangements</option>{[...new Set(items.map(i => i.category))].sort().map(c => <option key={c}>{c}</option>)}</select></label><label>Style<select value={style} onChange={e => setStyle(e.target.value)}><option value="">All styles</option>{styles.map(s => <option key={s}>{s}</option>)}</select></label><label>Colour<input value={colour} onChange={e => setColour(e.target.value)} placeholder="White, green…" /></label><label>Season<select value={season} onChange={e => setSeason(e.target.value)}><option value="">All seasons</option>{['Any season', 'Spring', 'Summer', 'Autumn', 'Winter'].map(s => <option key={s}>{s}</option>)}</select></label><label>Price from (£)<input type="number" min="0" value={min} onChange={e => setMin(e.target.value)} /></label><label>Price up to (£)<input type="number" min="0" value={max} onChange={e => setMax(e.target.value)} /></label></div>
    {filtered.length ? <><div className="ops-visual-grid">{filtered.slice(0, limit).map(i => <article className="ops-inspiration-card" key={i.id}><Photo src={i.images[0]?.url} alt={i.name} /><div className="ops-card-content"><p className="eyebrow">{i.category} · {i.occasion}</p><h3>{i.name}</h3><p>{i.description}</p><p className="ops-muted">{[i.style, i.palette, i.season, i.size].filter(Boolean).join(' · ')}</p><strong>{money(i.priceFrom)}–{money(i.priceTo)}</strong><span className="ops-price-label">Estimated price each</span>{i.images.length > 1 && <details><summary>More photographs</summary><div className="ops-photo-row">{i.images.slice(1).map(a => <Photo key={a.id} src={a.url} alt={a.name} />)}</div></details>}{onSelect && <div className="ops-card-select"><label>Quantity<input aria-label={`Quantity for ${i.name}`} type="number" min="1" max="1000" value={quantities[i.id] || 1} onChange={e => setQuantities({ ...quantities, [i.id]: Math.max(1, Math.floor(Number(e.target.value))) })} /></label><button type="button" className="button" onClick={() => onSelect(i, quantities[i.id] || 1)}>Add to my plan</button></div>}{onEdit && <div className="ops-toolbar"><Status>{i.active ? 'Active' : 'Inactive'}</Status><button type="button" onClick={() => onEdit(i)}>Edit inspiration</button></div>}</div></article>)}</div>{filtered.length > limit && <button type="button" onClick={() => setLimit(limit + 12)}>Show more designs</button>}</> : <Empty title={items.length ? 'No designs match these filters' : 'Your inspiration collection starts here'}><p>{onEdit ? 'Add photographs and guide prices for the designs you love making.' : 'The studio can add ideas for your occasion during your consultation.'}</p></Empty>}
    <p className="ops-estimate-note">Estimated prices are a guide. Final pricing depends on flower choice, seasonality, availability and final design. Selecting inspiration does not reserve or deduct stock.</p>
  </section>;
}
export default function InspirationCatalogue({ data, save, onDirty }: { data: StudioData; save: SaveData; onDirty: () => void }) {
  const [editing, setEditing] = useState<InspirationItem | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [occasion, setOccasion] = useState('');
  const ops = { ...emptyOperations(), ...data.operations };
  return <><Heading eyebrow="A COLLECTION OF POSSIBILITIES" title="Inspiration Catalogue"><p>Reusable visual ideas and guide prices for meaningful consultations.</p></Heading><div className="ops-toolbar"><button type="button" className="button" onClick={() => setEditing(blank())}>+ Add inspiration design</button><label>Occasion<select value={occasion} onChange={e => setOccasion(e.target.value)}><option value="">All occasions</option>{['Wedding', 'Funeral', 'Corporate', 'Other'].map(o => <option key={o}>{o}</option>)}</select></label></div>
    {editing ? <form className="ops-panel" onChange={onDirty} onSubmit={async e => { e.preventDefault(); if (editing.priceTo < editing.priceFrom) return setError('The upper guide price must be at least the lower price.'); setBusy(true); try { if (await save({ ...data, operations: { ...ops, catalogue: [editing, ...ops.catalogue.filter(i => i.id !== editing.id)] } }, 'Inspiration saved. No inventory changed.')) setEditing(null); } finally { setBusy(false); } }}><h2>{editing.name || 'New inspiration'}</h2><Fields value={editing} onChange={setEditing} fields={[{ key: 'name', label: 'Design name', required: true }, { key: 'category', label: 'Arrangement type', required: true }, { key: 'occasion', label: 'Occasion', options: ['Wedding', 'Funeral', 'Corporate', 'Other'] }, { key: 'style', label: 'Style', options: styles }, { key: 'palette', label: 'Colour palette' }, { key: 'season', label: 'Season', options: ['Any season', 'Spring', 'Summer', 'Autumn', 'Winter'] }, { key: 'flowers', label: 'Flower types' }, { key: 'size', label: 'Approximate size' }, { key: 'stemRange', label: 'Approximate stem range (optional)' }, { key: 'tags', label: 'Tags' }, { key: 'priceFrom', label: 'Estimated price from (£)', type: 'number' }, { key: 'priceTo', label: 'Estimated price to (£)', type: 'number' }, { key: 'description', label: 'Description for clients', type: 'textarea' }, { key: 'active', label: 'Show in client inspiration', type: 'checkbox' }]} /><Assets value={editing.images} imagesOnly label="Add inspiration photographs" onChange={images => { setEditing({ ...editing, images }); onDirty(); }} /><details><summary>Use an existing wedding photograph</summary><div className="ops-photo-picker">{['02', '03', '04', '05', '07', '09'].map(n => <button type="button" key={n} aria-label={`Choose wedding photograph ${n}`} onClick={() => { setEditing({ ...editing, images: [...editing.images, { id: newId(), name: `Wedding inspiration ${n}`, url: `/assets/weddings/wedding-${n}.jpg`, type: 'image/jpeg' }].slice(0, 12) }); onDirty(); }}><Photo src={`/assets/weddings/wedding-${n}.jpg`} alt={`Wedding photograph ${n}`} /></button>)}</div></details>{error && <p role="alert">{error}</p>}<div className="ops-toolbar"><button disabled={busy} className="button">{busy ? 'Saving…' : 'Save inspiration'}</button><button type="button" disabled={busy} onClick={() => { if (confirm('Close this editor? Unsaved changes will be lost.')) setEditing(null); }}>Close editor</button></div></form> : <CatalogueBrowse items={ops.catalogue} occasion={occasion} onEdit={i => setEditing(structuredClone(i))} />}</>;
}
