'use client';
import { useState } from 'react';
import { money } from '@/lib/pricing';
import { profitLabels, profitModel, type ProfitInput } from '@/lib/profitability';
export default function ProfitabilityPanel({ input, title = 'Profitability', compact = false, labour }: { input: ProfitInput; title?: string; compact?: boolean; labour?: { hours: number; rate: number } }) {
  const [simulation, setSimulation] = useState<ProfitInput | null>(null);
  const [labourHours, setLabourHours] = useState(labour?.hours ?? 1); const [labourRate, setLabourRate] = useState(labour?.rate ?? input.labour);
  const [discount, setDiscount] = useState(0); const [vatRate, setVatRate] = useState(input.selling ? input.vat / input.selling * 100 : 20);
  const model = profitModel(simulation ? { ...simulation, selling: Math.max(0, simulation.selling - discount), vat: Math.max(0, simulation.selling - discount) * vatRate / 100 } : input);
  return <section className={`ops-profit-panel ${compact ? 'ops-profit-compact' : ''} ops-profit-${model.rating.toLowerCase().replace(' ', '-')}`}><div className="ops-section-title"><h2>{title}</h2><span className="ops-margin-rating">{model.rating} · {model.margin}%</span></div>
    <div className="ops-profit-cards"><div><span>Selling price · ex VAT</span><strong>{money(model.selling)}</strong></div><div><span>Total business costs</span><strong>{money(model.cost)}</strong></div><div><span>Gross profit</span><strong>{money(model.profit)}</strong></div><div className="ops-retained"><span>Estimated net profit after tax</span><strong>{money(model.retained)}</strong></div></div>
    <details open={!compact}><summary>Cost &amp; tax breakdown</summary><dl className="ops-cost-breakdown">{Object.entries(profitLabels).map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{money(model[key as keyof typeof profitLabels])}</dd></div>)}<div><dt>Selling price · inc VAT</dt><dd>{money(model.gross)}</dd></div><div><dt>VAT charged</dt><dd>{money(model.vat)}</dd></div><div><dt>Estimated corporation tax · {model.taxRate}%</dt><dd>{money(model.tax)}</dd></div><div><dt>Projected cash retained</dt><dd>{money(model.retained)}</dd></div></dl></details>
    <div className="ops-money-flow" aria-label="Money flow"><div><span>Money in</span><b>{money(model.gross)}</b></div><span aria-hidden="true">↓</span><div><span>Business costs</span><b>−{money(model.cost)}</b></div><span aria-hidden="true">↓</span><div><span>VAT charged</span><b>−{money(model.vat)}</b></div><span aria-hidden="true">↓</span><div><span>Estimated tax</span><b>−{money(model.tax)}</b></div><span aria-hidden="true">↓</span><div className="ops-money-kept"><span>Money kept · projected</span><b>{money(model.retained)}</b></div></div>
    <div className="ops-coach"><h3>Pricing insights</h3>{model.profit < 0 ? <p>This work is projected to lose {money(-model.profit)} before tax.</p> : model.margin >= 40 ? <p>This design meets a 40% gross-margin target.</p> : <p>{model.cost === 0 && model.selling === 0 ? 'Add costs and a selling price to see useful margin guidance.' : <>Increasing the price by <b>{money(model.targetIncrease)} ex VAT</b> would reach a 40% gross margin, with these costs unchanged.</>}</p>}{model.labourShare > 25 && <p>Labour represents {model.labourShare}% of the selling price. Review the making time and hourly rate.</p>}<small>Calculated guidance. Prices only change when you choose to edit and save them.</small></div>
    <details className="ops-simulator"><summary>Live profit simulator</summary><p>Try a scenario here. It does not change your saved price or stock.</p>{!simulation ? <button type="button" onClick={() => { setSimulation({ ...input }); setDiscount(0); setLabourHours(labour?.hours ?? 1); setLabourRate(labour?.rate ?? input.labour); setVatRate(input.selling ? input.vat / input.selling * 100 : 0); }}>Try a pricing scenario</button> : <><div className="ops-fields">{[{ key: 'selling', label: 'Selling price before discount · ex VAT (£)' }, { key: 'flower', label: 'Flower costs (£)' }, { key: 'supplier', label: 'Supplier charges (£)' }, { key: 'taxRate', label: 'Estimated corporation tax (%)' }].map(f => <label key={f.key}>{f.label}<input type="number" min="0" step="any" value={simulation[f.key as keyof ProfitInput]} onChange={e => setSimulation({ ...simulation, [f.key]: Number(e.target.value) })} /></label>)}<label>Labour hours<input type="number" min="0" step="any" value={labourHours} onChange={e => { const hours = Number(e.target.value); setLabourHours(hours); setSimulation({ ...simulation, labour: hours * labourRate }); }} /></label><label>Hourly rate (£)<input type="number" min="0" step="any" value={labourRate} onChange={e => { const rate = Number(e.target.value); setLabourRate(rate); setSimulation({ ...simulation, labour: labourHours * rate }); }} /></label><label>Discount (£)<input type="number" min="0" step="any" value={discount} onChange={e => setDiscount(Number(e.target.value))} /></label><label>VAT rate (%)<input type="number" min="0" max="100" value={vatRate} onChange={e => setVatRate(Number(e.target.value))} /></label></div><button type="button" onClick={() => setSimulation(null)}>Reset to saved / draft figures</button></>}</details>
    <p className="ops-finance-note">Planning estimates assume full customer payment and all listed costs paid. Corporation tax applies the editable rate to positive profit; actual tax depends on the business’s overall taxable profit and reliefs. VAT shown is output VAT before recoverable input VAT or adjustments. These figures are not a bank balance or tax return.</p>
  </section>;
}
