'use client';
import { useMemo, useState } from 'react';
import ProfitabilityPanel from './profitability-panel';
import RecipeIngredients from './recipe-ingredients';
import { recipeProfitInput } from '@/lib/profitability';
import Dialog from '../dialog';
import { calculateTotals, money } from '@/lib/pricing';
import { recipeAvailability, recipeRequirements } from '@/lib/studio-commands';
import { duplicateRecipe, newId, newRecipe } from '@/lib/operations-model';
import type { StudioData, Quote } from '@/lib/types';
import { Assets, Fields, Heading, Photo, Empty, Status, type RunCommand } from './ops-ui';

export default function RecipeBuilder({ data, recipe, onChange, command, onEvent, showTemplates = false }: { showTemplates?: boolean; onEvent?: (id: string) => void; data: StudioData; recipe: Quote; onChange: (q: Quote) => void; command: RunCommand }) {
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState(showTemplates ? 'Templates' : 'All'); const [confirm, setConfirm] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [allowShortages, setAllowShortages] = useState(false); const [reason, setReason] = useState('');
  const [showLibrary, setShowLibrary] = useState(showTemplates);
  const totals = useMemo(() => calculateTotals(recipe), [recipe]);
  const purchased = data.jobs.find(j => j.id === recipe.id);
  const current = purchased ? { ...recipe, commitments: purchased.commitments } : recipe;
  const availability = recipeAvailability(data, current);
  const library = [...data.quotes, ...data.jobs].filter(q => `${q.name || ''} ${q.clientName} ${q.occasion}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'All' || filter === 'Favourites' ? filter !== 'Favourites' || q.favourite : filter === 'Templates' ? q.isTemplate : (q.status || ('wonAt' in q ? 'PURCHASED' : 'QUOTE')) === filter));
  const choose = (next: Quote) => { const saved = [...data.quotes, ...data.jobs].find(r => r.id === recipe.id); if ((recipe.name || recipe.clientName || recipe.lines.length) && JSON.stringify(saved) !== JSON.stringify(recipe) && !confirmDiscard()) return; onChange(next); setReason(''); };
  const confirmDiscard = () => globalThis.confirm('Discard unsaved changes to this recipe?');
  const change = (updates: Partial<Quote>) => onChange({ ...recipe, ...updates });
  const save = async (status: 'DRAFT' | 'QUOTE') => {
    setBusy(true); setError(''); try { const result = await command({ type: 'saveRecipe', recipe, status }); if (result) { const saved = result.quotes.find(q => q.id === recipe.id); if (saved) onChange(saved); } return result; } finally { setBusy(false); }
  };
  return <div className="ops-recipe"><Heading eyebrow="FROM AN IDEA TO A FINISHED DESIGN" title="Recipe Builder"><p>Design once. Save a draft, prepare a quote, then commit stock when the client purchases.</p></Heading>
    {recipe.planId && onEvent && <button className="back-button" type="button" onClick={() => onEvent(recipe.planId!)}>← Back to floral plan</button>}
    <div className="ops-toolbar"><button type="button" className="button" onClick={() => { choose(newRecipe(data)); }}>+ New recipe</button><button type="button" onClick={() => setShowLibrary(!showLibrary)}>{showLibrary ? 'Hide' : 'Show'} recipe library</button><details className="studio-recipe-tools"><summary>More recipe tools</summary><div className="ops-toolbar"><button type="button" onClick={() => choose(duplicateRecipe(recipe))}>Duplicate recipe</button><button type="button" onClick={() => choose(duplicateRecipe(recipe, true))}>Create template draft</button><button type="button" aria-pressed={recipe.favourite === true} onClick={() => change({ favourite: !recipe.favourite })}>{recipe.favourite ? '★ Favourited' : '☆ Favourite'}</button></div></details></div>
    {showLibrary && <section className="ops-library"><div className="ops-toolbar"><label>Find a recipe<input type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Design, client or event" /></label><label>Show<select value={filter} onChange={e => setFilter(e.target.value)}>{['All', 'DRAFT', 'QUOTE', 'PURCHASED', 'Templates', 'Favourites'].map(s => <option key={s}>{s}</option>)}</select></label></div>{library.length ? <div className="ops-recipe-strip">{library.slice(0, 30).map(q => <button type="button" key={q.id} onClick={() => { choose(structuredClone(q)); }}><Photo src={q.inspirationImage} alt={q.name || q.occasion} /><span><Status>{q.isTemplate ? 'TEMPLATE' : 'stockReturned' in q && q.stockReturned ? 'CANCELLED' : q.status || ('wonAt' in q ? 'PURCHASED' : 'QUOTE')}</Status><strong>{q.name || q.occasion}</strong><small>{q.clientName || 'Reusable design'} · {q.quantity || 1} required</small></span></button>)}</div> : <p>No matching recipes yet. Start with a new design or create one from a client’s inspiration.</p>}</section>}
    <div className="ops-recipe-grid"><section className="ops-panel">
      <div className="ops-section-title"><h2>{purchased ? 'Purchased recipe' : 'Your design'}</h2><Status>{purchased ? 'PURCHASED' : recipe.status || 'DRAFT'}</Status></div>
      <Fields value={recipe} onChange={onChange} fields={[{ key: 'name', label: 'Arrangement name', required: true }, { key: 'quantity', label: 'Quantity required', type: 'number' }, { key: 'clientName', label: 'Client / couple' }]} />
      <details className="studio-more-details"><summary>Client & event details{recipe.eventDate && ` · ${recipe.eventDate}`}</summary><Fields value={recipe} onChange={onChange} fields={[{key:'contact',label:'Phone or email'},{key:'occasion',label:'Occasion',options:['Bouquet','Wedding','Funeral','Corporate']},{key:'eventDate',label:'Event / order date',type:'date'}]} />
      <label className="ops-block-label">Attach to an event<select value={recipe.planId || ''} disabled={!!purchased} onChange={e => { const plan = data.plans.find(p => p.id === e.target.value); change({ planId: plan?.id, clientName: plan?.clientName || recipe.clientName, customerId: plan?.customerId, eventDate: plan?.eventDate || recipe.eventDate, occasion: plan?.type || recipe.occasion, contact: plan?.contact || recipe.contact }); }}><option value="">Standalone order / template</option>{data.plans.map(p => <option key={p.id} value={p.id}>{p.clientName} · {p.type} · {p.eventDate || 'Date to confirm'}</option>)}</select></label></details>
      <div className="studio-recipe-image"><Photo src={recipe.inspirationImage} alt={recipe.name || 'Arrangement inspiration'} /><div><p>{recipe.palette || 'Start with a flower, a colour or a favourite photograph.'}</p><Assets imagesOnly max={1} label={recipe.inspirationImage ? 'Replace inspiration photograph' : 'Add inspiration photograph'} value={[]} onChange={assets => { const asset = assets[assets.length-1]; if (asset) change({inspirationImage:asset.url}); }} />{recipe.inspirationImage && <button type="button" onClick={() => change({inspirationImage:''})}>Remove photograph</button>}</div></div>
      <RecipeIngredients data={data} lines={recipe.lines} onChange={lines => change({ lines })} />
      <div className="studio-material-estimate"><span>Estimated materials</span><strong>{money(totals.materialCost)}</strong></div><Fields value={recipe} onChange={onChange} fields={[{key:'sellingPriceExVat',label:'Selling price (£, before VAT)',type:'number',hint:`Optional. Suggested price: ${money(totals.netTotal)} before VAT.`}]} /><details className="studio-more-details"><summary>Time, delivery & advanced pricing</summary><Fields value={recipe} onChange={onChange} fields={[{ key: 'labourHours', label: 'Labour hours per arrangement', type: 'number' }, { key: 'labourRate', label: 'Labour rate (£ / hour)', type: 'number' }, { key: 'wastagePercent', label: 'Waste allowance (%)', type: 'number' }, { key: 'markupPercent', label: 'Markup (%)', type: 'number' }, { key: 'deliveryFee', label: 'Delivery charge (£, whole recipe)', type: 'number' }, { key: 'discount', label: 'Discount (£, whole recipe)', type: 'number' }, { key: 'corporationTaxRate', label: 'Estimated corporation tax (%)', type: 'number' }, { key: 'deliveryCost', label: 'Delivery cost (£)', type: 'number' }, { key: 'setupCost', label: 'Installation / setup cost (£)', type: 'number' }, { key: 'collectionCost', label: 'Collection cost (£)', type: 'number' }, { key: 'supplierCharges', label: 'Supplier charges beyond material prices (£)', type: 'number' }, { key: 'additionalExpenses', label: 'Additional expenses (£)', type: 'number' }, { key: 'vatRate', label: 'VAT rate (%)', type: 'number' }, { key: 'vatApplies', label: 'Apply VAT', type: 'checkbox' }, { key: 'instructions', label: 'Making instructions', type: 'textarea' }, { key: 'notes', label: 'Internal notes', type: 'textarea' }]} /></details>
    </section><aside className="ops-panel ops-recipe-summary"><h2>Your finished design</h2><p>{recipe.quantity || 1} arrangement{(recipe.quantity || 1) === 1 ? '' : 's'}</p><ProfitabilityPanel key={recipe.id} compact labour={{ hours: recipe.labourHours * (recipe.quantity || 1), rate: recipe.labourRate }} input={recipeProfitInput(recipe, data.settings.corporationTaxRate)} />
      <details className="studio-more-details"><summary>Stock availability{availability.some(a => a.shortage) ? ' · Items need ordering' : ''}</summary>
      <h3>Inventory availability</h3>{availability.length ? availability.map(a => <p key={a.inventoryId} className={a.shortage ? 'ops-warning' : ''}><b>{a.name}</b><br />{a.quantity} required · {a.available} available{a.committed > 0 && ` · ${a.committed} committed`}{a.shortage > 0 && ` · ${a.shortage} short`}</p>) : <p>Linked stock availability will appear here.</p>}
      </details><div className="ops-recipe-actions">{!purchased ? <><button disabled={busy} type="button" className="button" onClick={() => void save('QUOTE')}>Save as Quote</button><button disabled={busy || recipe.isTemplate} type="button" className="button" onClick={() => { setAllowShortages(false); setConfirm(true); }}>Mark as Purchased</button><small>Saving a quote never deducts inventory.</small><button disabled={busy} type="button" onClick={() => void save('DRAFT')}>Save unfinished draft</button></> : <><label>Reason for amendment<textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="What changed, and why?" /></label><button disabled={busy || !!purchased.stockReturned} type="button" className="button" onClick={async () => { setBusy(true); try { const result = await command({ type: 'amendRecipe', recipe, reason, allowShortages: false }); if (result) onChange(result.jobs.find(j => j.id === recipe.id)!); } finally { setBusy(false); } }}>Save amendment with audit note</button><p>The accepted event quotation stays on record. Stock changes are recorded in the audit history.</p></>}</div>
      {error && <p role="alert">{error}</p>}
    </aside></div>
    {confirm && <Dialog label="Confirm recipe purchase" onClose={() => !busy && setConfirm(false)} className="ops-confirm-dialog"><h2>Confirm purchase</h2><p><b>{recipe.clientName || 'Client name required'}</b> · {recipe.name || recipe.occasion}</p><p>{recipe.eventDate || 'Date to confirm'} · {recipe.quantity || 1} arrangement(s)</p><strong className="ops-large-price">{money(totals.grossTotal)}</strong><h3>Stock to commit</h3>{availability.map(a => <p key={a.inventoryId}>{a.name}: {a.quantity} required, {Math.min(a.quantity, a.available)} can be committed{a.shortage > 0 && <b> · {a.shortage} short</b>}</p>)}{availability.some(a => a.shortage > 0) && <label className="ops-check"><input type="checkbox" checked={allowShortages} onChange={e => setAllowShortages(e.target.checked)} />Confirm purchase with these shortages and include them in purchase requirements</label>}<p>Available stock is committed once. Production records consumption later without a second deduction. This records the purchase; it does not take payment.</p><div className="ops-toolbar"><button disabled={busy} type="button" onClick={() => setConfirm(false)}>Back to recipe</button><button disabled={busy || (availability.some(a => a.shortage > 0) && !allowShortages)} type="button" className="button" onClick={async () => { setBusy(true); try { const saved = await command({ type: 'saveRecipe', recipe, status: 'QUOTE' }); if (!saved) return; const result = await command({ type: 'purchaseRecipe', recipeId: recipe.id, allowShortages }); if (result) { onChange(result.jobs.find(j => j.id === recipe.id)!); setConfirm(false); } } finally { setBusy(false); } }}>{busy ? 'Confirming…' : 'Confirm Purchased'}</button></div></Dialog>}
  </div>;
}
