'use client';
import { useMemo, useState } from 'react';
import { studioInsights } from '@/lib/studio-insights';
import { money } from '@/lib/pricing';
import type { StudioData } from '@/lib/types';

const day = (date: Date) => new Intl.DateTimeFormat('en-CA', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(date);
export default function StudioInsights({ data }: { data: StudioData }) {
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [sort, setSort] = useState('profit');
  const insights = useMemo(() => studioInsights(data, from, to), [data, from, to]);
  const rows = [...insights.rows].sort((a, b) => sort === 'waste' ? b.wasteCost - a.wasteCost : sort === 'sold' ? b.sold - a.sold : b.profit - a.profit);
  const max = Math.max(1, ...insights.trend.flatMap(item => [item.waste, Math.abs(item.contribution)]));
  const range = (days: number | null) => { if (days === null) { setFrom(''); setTo(''); } else { const now = new Date(); setTo(day(now)); now.setDate(now.getDate() - days + 1); setFrom(day(now)); } };
  return <section className="insights-view">
    <p className="eyebrow">WASTAGE &amp; FLOWER PERFORMANCE</p><h1>Wastage &amp; flower performance</h1>
    <p className="insights-intro">Track logged losses and the flowers used in won jobs, over any period.</p>
    <div className="insights-filters"><div className="insights-presets"><button onClick={() => range(30)}>Last 30 days</button><button onClick={() => range(90)}>Last 90 days</button><button onClick={() => range(365)}>Last year</button><button onClick={() => range(null)}>All time</button></div><label>From<input type="date" value={from} max={to || undefined} onChange={event => setFrom(event.target.value)} /></label><label>To<input type="date" value={to} min={from || undefined} onChange={event => setTo(event.target.value)} /></label></div>
    {from && to && from > to ? <p className="empty-state" role="alert">Choose an end date after the start date.</p> : <>
      <div className="insights-metrics"><article><small>Logged wastage at cost</small><b>{money(insights.wasteCost)}</b><span>{insights.wasted} stock units lost</span></article><article><small>Flowers used at cost</small><b>{money(insights.usedCost)}</b><span>{insights.jobCount} won job{insights.jobCount === 1 ? '' : 's'}</span></article><article><small>Estimated flower profit</small><b>{money(insights.profit)}</b><span>After logged wastage</span></article></div>
      <details className="insights-method"><summary>How these figures are calculated</summary><p>Jobs use their won date; wastage uses its logged date. All amounts exclude VAT. A job’s revenue and profit are shared across its flower and material lines in proportion to each line’s purchase cost. This estimates a flower’s contribution because individual selling prices are not recorded. Logged wastage is then deducted from the matching flower.</p><p>The quote’s wastage allowance is already included in job costs. The loss log records additional stock written off. Flowers are grouped by their saved name and stock unit; older records without units use their inventory unit, or stems if the original stock is gone. Returned jobs are excluded from sold quantities and contribution.</p>{insights.returnedJobs > 0 && <p>{insights.returnedJobs} returned job{insights.returnedJobs === 1 ? '' : 's'} excluded in this period.</p>}{insights.unallocatedJobs > 0 && <p>{insights.unallocatedJobs} job{insights.unallocatedJobs === 1 ? '' : 's'} with no line costs cannot be allocated to flower profit.</p>}</details>
      <section className="insights-panel"><h2>Through the seasons</h2><p className="insights-legend"><span>■ Estimated flower contribution</span><span>■ Logged wastage cost</span></p>{insights.trend.length ? <div className="insights-chart" role="list" aria-label="Monthly flower contribution and wastage">{insights.trend.map(item => <div className="insights-month" role="listitem" key={item.month}><span>{new Date(item.month + '-01T12:00:00').toLocaleDateString('en-GB', { month: 'short', year: '2-digit' })}</span><div><div className="insights-bar contribution" style={{ width: `${Math.max(2, Math.abs(item.contribution) / max * 100)}%` }} /><div className="insights-bar waste" style={{ width: `${Math.max(2, item.waste / max * 100)}%` }} /></div><span>{money(item.contribution)}<small>{money(item.waste)} wastage</small></span></div>)}</div> : <p className="empty-state">No won jobs or logged wastage in this period. Figures appear as you use inventory and record losses.</p>}</section>
      <section className="insights-panel"><div className="insights-table-heading"><div><h2>Flower performance</h2><p>Compare contribution, quantity used and stock lost.</p></div><label>Sort by<select value={sort} onChange={event => setSort(event.target.value)}><option value="profit">Estimated profit</option><option value="waste">Highest wastage</option><option value="sold">Most used</option></select></label></div>{rows.length ? <div className="insights-table-scroll"><table><thead><tr><th>Flower</th><th>Used / sold</th><th>Allocated revenue</th><th>Logged wastage</th><th>Estimated profit</th></tr></thead><tbody>{rows.map(row => <tr key={`${row.name}-${row.unit}`}><th scope="row">{row.name}<small>{row.unit === 'stem' ? 'Stems' : row.unit === 'bunch' ? 'Bunches' : 'Units'}</small></th><td>{row.sold}<small>{money(row.cost)} at cost</small></td><td>{money(row.revenue)}</td><td>{money(row.wasteCost)}<small>{row.wasted} lost</small></td><td className={row.profit < 0 ? 'insights-negative' : 'insights-positive'}>{money(row.profit)}</td></tr>)}</tbody></table></div> : <p className="empty-state">There is no flower performance to compare yet.</p>}</section>
    </>}
  </section>;
}
