'use client';
import { calendarItems, day, stockForecast } from '@/lib/operations-model';
import type { StudioData, WeddingPlan } from '@/lib/types';
import { Photo } from './ops-ui';

type Props = { data: StudioData; open: (section: string, id?: string) => void; newClient: () => void; newEvent: (type: WeddingPlan['type']) => void; newRecipe: () => void };
export default function StudioHome({ data, open, newClient, newEvent, newRecipe }: Props) {
  const today = day();
  const hour = Number(new Intl.DateTimeFormat('en-GB', { timeZone: 'Europe/London', hour: 'numeric', hourCycle: 'h23' }).format(new Date()));
  const jobs = calendarItems(data).filter(i => i.date === today);
  const events = data.plans.filter(p => p.eventDate >= today && p.type !== 'Funeral').sort((a,b) => a.eventDate.localeCompare(b.eventDate)).slice(0,3);
  const quotes = (data.operations?.eventQuotes || []).filter(q => q.status === 'QUOTE' && q.approval?.status !== 'Approved');
  const standalone = data.quotes.filter(q => !q.isTemplate && q.status !== 'DRAFT' && !(data.operations?.eventQuotes || []).some(e => e.recipeIds.includes(q.id)));
  const low = stockForecast(data).filter(i => i.shortfall > 0);
  const recent = [...data.customers].sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0,4);
  return <div className="studio-calm-home"><header className="studio-welcome"><div><p className="eyebrow">YOUR DAY IN THE STUDIO</p><h1>Good {hour < 12 ? 'morning' : hour < 18 ? 'afternoon' : 'evening'}, Jade</h1><p>A little space to plan, create and bring beautiful flowers to life.</p></div><div className="studio-welcome-flower" aria-hidden="true">✾</div></header>
    <div className="studio-calm-actions" aria-label="Start something new"><button onClick={newClient}>+ New Client</button><button onClick={() => newEvent('Wedding')}>+ New Wedding</button><button onClick={() => newEvent('Funeral')}>+ New Funeral</button><button onClick={newRecipe}>+ Build Recipe</button><button onClick={newRecipe}>+ Create Quote</button></div>
    <div className="studio-home-grid"><section className="ops-panel"><div className="ops-section-title"><h2>Today’s jobs</h2><button onClick={() => open('calendar')}>View diary →</button></div>{jobs.length ? jobs.map(j => <button className="studio-simple-row" key={j.id} onClick={() => open(j.tab,j.recordId)}><span><b>{j.title}</b><small>{j.kind}{j.time && ` · ${j.time}`}</small></span><span>→</span></button>) : <p className="studio-calm-empty">A little breathing room. Nothing scheduled for today.</p>}</section>
    <section className="ops-panel"><div className="ops-section-title"><h2>Upcoming weddings & events</h2><button onClick={() => open('events')}>View all →</button></div>{events.length ? events.map(p => <button className="studio-simple-row" key={p.id} onClick={() => open('clients',p.id)}><span><b>{p.clientName}</b><small>{p.eventDate} · {p.venue || 'Venue to confirm'}</small></span><span>→</span></button>) : <p className="studio-calm-empty">Your next celebration starts with a conversation.</p>}</section>
    <section className="ops-panel"><h2>Quotes awaiting approval</h2>{quotes.length + standalone.length ? <>{quotes.slice(0,4).map(q => <button className="studio-simple-row" key={q.id} onClick={() => open('clients',q.planId)}><span><b>{q.clientName}</b><small>{q.name}</small></span><span>→</span></button>)}{standalone.slice(0,4).map(q => <button className="studio-simple-row" key={q.id} onClick={() => open('calculator',q.id)}><span><b>{q.clientName || 'Your quote'}</b><small>{q.name || q.occasion}</small></span><span>→</span></button>)}</> : <p className="studio-calm-empty">No quotes waiting just now.</p>}</section>
    <section className="ops-panel"><h2>Flowers needing attention</h2>{low.length ? low.slice(0,5).map(i => <button className="studio-simple-row" key={i.inventoryId} onClick={() => open('suppliers')}><span><b>{i.name}</b><small>{i.shortfall} more needed for confirmed work</small></span><span>→</span></button>) : <p className="studio-calm-empty">No stock shortages for upcoming confirmed work.</p>}<button onClick={() => open('inventory')}>Open inventory →</button></section></div>
    <section className="studio-recent-clients"><div className="ops-section-title"><h2>Recent clients</h2><button onClick={() => open('clients')}>Your client book →</button></div><div className="studio-client-pills">{recent.length ? recent.map(c => <button key={c.id} onClick={() => open('clients',c.id)}><span aria-hidden="true">{c.name.slice(0,1)}</span>{c.name}</button>) : <p>Your client book will grow with each new conversation.</p>}</div></section>
  </div>;
}

export function EventDirectory({ data, funeral, open, create }: { data: StudioData; funeral: boolean; open: (plan: WeddingPlan) => void; create: (type: WeddingPlan['type']) => void }) {
  const plans = data.plans.filter(p => funeral ? p.type === 'Funeral' : p.type !== 'Funeral').sort((a,b) => b.eventDate.localeCompare(a.eventDate));
  return <div className="studio-event-directory"><header className="ops-heading"><p className="eyebrow">{funeral ? 'FLOWERS TO REMEMBER' : 'FLOWERS FOR THEIR DAY'}</p><h1>{funeral ? 'Funerals' : 'Weddings & Events'}</h1><p>{funeral ? 'Thoughtful tributes, planned with care.' : 'From the first idea to the last stem in place.'}</p></header><div className="ops-toolbar"><button className="button" onClick={() => create(funeral ? 'Funeral' : 'Wedding')}>+ New {funeral ? 'Funeral' : 'Wedding'}</button>{!funeral && <button onClick={() => create('Corporate')}>+ New Event</button>}</div><div className="ops-record-grid">{plans.map(p => <button className="ops-record-card studio-event-card" key={p.id} onClick={() => open(p)}><Photo src={p.inspiration?.[0]?.image || p.references?.[0]?.dataUrl} alt={`${p.clientName} floral inspiration`} /><div><small>{p.type} · {p.status || 'Enquiry'}</small><h2>{p.clientName}</h2><p>{p.eventDate || 'Date to confirm'} · {p.venue || 'Venue to confirm'}</p><span>Open floral plan →</span></div></button>)}</div>{!plans.length && <section className="ops-panel studio-calm-empty">Start a new floral plan. We’ll guide you through each step.</section>}</div>;
}
