'use client';
import { useState } from 'react';
import { calendarItems, day, addDays, stockForecast, actionItems } from '@/lib/operations-model';
import type { StudioData, WeddingPlan } from '@/lib/types';
import { Photo, type SaveData } from './ops-ui';
import { SectionHeading, EmptyState, SummaryCard, QuickAction, StudioIcon } from './design-system';

type Props = { data: StudioData; open: (section: string, id?: string) => void; save: SaveData; newClient: () => void; newEvent: (type: WeddingPlan['type']) => void; newRecipe: () => void; addInvoice: () => void };
const dateLabel = (value: string, short = false) => value ? new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: short ? 'short' : 'long', ...(short ? {} : { year: 'numeric' }), timeZone: 'Europe/London' }).format(new Date(`${value}T12:00:00Z`)) : 'Date to confirm';
export default function StudioHome({ data, open, save, newClient, newEvent, newRecipe, addInvoice }: Props) {
  const today = day(); const [taskBusy, setTaskBusy] = useState<string | null>(null);
  const hour = Number(new Intl.DateTimeFormat('en-GB', { timeZone: 'Europe/London', hour: 'numeric', hourCycle: 'h23' }).format(new Date()));
  const calendar = calendarItems(data); const jobs = calendar.filter(i => i.date === today);
  const upcoming = data.plans.filter(p => p.eventDate >= today && !['Completed','Cancelled'].includes(p.status || '')).sort((a,b) => a.eventDate.localeCompare(b.eventDate));
  const next = upcoming[0]; const thisMonth = upcoming.filter(p => p.eventDate.slice(0,7) === today.slice(0,7));
  const low = stockForecast(data).filter(i => i.shortfall > 0);
  const priorities = actionItems(data).filter(i => !i.id.startsWith('stock-')).slice(0,4);
  const tasks = (data.operations?.tasks || []).filter(t => !t.completed && (!t.due || t.due <= today)).slice(0,5);
  const recent = [...data.customers].sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0,4);
  const firstDay = new Date(`${today.slice(0,7)}-01T12:00:00Z`); const offset = (firstDay.getUTCDay() + 6) % 7;
  const days = new Date(Date.UTC(firstDay.getUTCFullYear(), firstDay.getUTCMonth()+1,0)).getUTCDate();
  const eventImage = next?.inspiration?.[0]?.image || next?.references?.[0]?.dataUrl;
  const toggleTask = async (id: string) => { if (!data.operations || taskBusy) return; setTaskBusy(id); try { await save({ ...data, operations: { ...data.operations, tasks: data.operations.tasks.map(t => t.id === id ? { ...t, completed: true } : t) } }, 'Task completed. A little more ready.'); } finally { setTaskBusy(null); } };
  return <div className="atelier-home">
    <header className="atelier-welcome"><div><p className="eyebrow">YOUR DAY IN THE STUDIO</p><h1>Good {hour < 12 ? 'morning' : hour < 18 ? 'afternoon' : 'evening'}, Jade</h1><p>Beautiful flowers. Brighter days.</p></div><div className="atelier-welcome-date"><time dateTime={today}>{new Intl.DateTimeFormat('en-GB', { weekday: 'long', day: 'numeric', month: 'long', timeZone: 'Europe/London' }).format(new Date())}</time><span>A little space to create.</span></div></header>
    <div className="atelier-summaries"><SummaryCard icon="events" label="Weddings" value={thisMonth.filter(p => p.type === 'Wedding').length} detail="Coming up this month" onClick={() => open('events')} /><SummaryCard icon="flower" label="Funerals" value={thisMonth.filter(p => p.type === 'Funeral').length} detail="Coming up this month" onClick={() => open('funerals')} /><SummaryCard icon="studio" label="Corporate events" value={thisMonth.filter(p => p.type === 'Corporate').length} detail="Coming up this month" onClick={() => open('events')} /><SummaryCard icon="delivery" label="Deliveries" value={(data.operations?.deliveries || []).filter(d => d.date >= today && d.date < addDays(today,7) && !['Delivered','Collected'].includes(d.status)).length} detail="In the next seven days" onClick={() => open('deliveries')} /></div>
    <div className="atelier-day-grid"><section className="atelier-card atelier-priorities"><SectionHeading title="Today’s priorities" action={<button onClick={() => open('tasks')}>View all →</button>} />
      {tasks.map(t => <div className="atelier-priority" key={t.id}><label className="atelier-task-check"><input aria-label={`Complete: ${t.title}`} type="checkbox" checked={false} disabled={!!taskBusy} onChange={() => void toggleTask(t.id)} /><span>{t.title}</span></label><span className={`atelier-due ${t.due && t.due < today ? 'overdue' : ''}`}>{taskBusy === t.id ? 'Saving…' : t.due && t.due < today ? 'Overdue' : t.due ? 'Today' : 'To do'}</span></div>)}
      {priorities.map(item => <button className="atelier-priority atelier-priority-link" key={item.id} onClick={() => open(item.tab,item.recordId)}><StudioIcon name="arrow" /><span><b>{item.title}</b><small>{item.detail}</small></span></button>)}
      {!tasks.length && !priorities.length && <EmptyState title="A little breathing room">You’re up to date. Your next priorities will appear here.</EmptyState>}
    </section>
    <section className="atelier-event-feature"><Photo src={eventImage || (next?.type === 'Funeral' ? '/assets/sympathy-spray.jpg' : '/assets/weddings/ceremony-celebration.webp')} alt={eventImage ? `${next?.clientName} floral inspiration` : 'Bramble & Petal floral portfolio'} /><div className="atelier-event-shade" /><div className="atelier-event-caption"><p className="eyebrow">{next ? `YOUR NEXT ${next.type.toUpperCase()}` : 'FROM THE STUDIO'}</p><h2>{next?.clientName || 'Beautiful things, thoughtfully made.'}</h2><p>{next ? `${dateLabel(next.eventDate,true)} · ${next.venue || 'Venue to confirm'}` : 'Your next celebration starts with a conversation.'}</p>{next && <span className="atelier-event-status">{next.status || 'Enquiry'}</span>}<button onClick={() => next ? open('clients',next.id) : newEvent('Wedding')}>{next ? 'View event' : 'Plan a wedding'} →</button>{!eventImage && <small>Studio portfolio inspiration</small>}</div></section>
    <aside className="atelier-card atelier-diary"><SectionHeading title={new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'Europe/London'}).format(new Date())} action={<button aria-label="Open calendar" onClick={() => open('calendar')}>↗</button>} /><div className="atelier-mini-calendar" aria-label="This month">{['M','T','W','T','F','S','S'].map((d,i) => <span className="atelier-calendar-day" key={`day-${i}`}>{d}</span>)}{Array.from({length: offset},(_,i) => <span key={`blank-${i}`} />)}{Array.from({length:days},(_,i) => { const date = `${today.slice(0,7)}-${String(i+1).padStart(2,'0')}`; const count = calendar.filter(c => c.date === date).length; return <button key={date} className={`${date === today ? 'is-today' : ''} ${count ? 'has-events' : ''}`} aria-label={`${dateLabel(date)}${date === today ? ', today' : ''}, ${count} scheduled items. Open calendar`} onClick={() => open('calendar')}>{i+1}</button>; })}</div><SectionHeading title="Today" action={<button onClick={() => open('calendar')}>View diary →</button>} /><div className="atelier-schedule">{jobs.length ? jobs.slice(0,5).map(j => <button key={j.id} onClick={() => open(j.tab,j.recordId)}><time>{j.time || 'All day'}</time><span><b>{j.title}</b><small>{j.kind}</small></span></button>) : <p>No appointments today.<br />Space to prepare for what’s next.</p>}</div></aside></div>
    <div className="atelier-quick-actions" aria-label="Quick actions"><QuickAction icon="events" label="New wedding" onClick={() => newEvent('Wedding')} /><QuickAction icon="clients" label="New client" onClick={newClient} /><QuickAction icon="flower" label="Create recipe" onClick={newRecipe} /><QuickAction icon="delivery" label="Log delivery" onClick={() => open('deliveries')} /><QuickAction icon="orders" label="Add invoice" onClick={addInvoice} /><QuickAction icon="waste" label="Record waste" onClick={() => open('inventory')} /></div>
    <div className="atelier-home-secondary"><section className="atelier-card"><SectionHeading title="Flowers needing attention" action={<button onClick={() => open('inventory')}>View flowers →</button>} />{low.length ? low.slice(0,4).map(i => <button className="atelier-priority atelier-priority-link" key={i.inventoryId} onClick={() => open('suppliers')}><StudioIcon name="flower" /><span><b>{i.name}</b><small>{i.shortfall} more needed for confirmed work</small></span></button>) : <p className="atelier-quiet"><StudioIcon name="check" />No shortages for upcoming confirmed work.</p>}</section><section className="atelier-card"><SectionHeading title="Your client book" action={<button onClick={() => open('clients')}>View all →</button>} /><div className="atelier-client-pills">{recent.length ? recent.map(c => <button key={c.id} onClick={() => open('clients',c.id)}><span>{c.name.slice(0,1)}</span><b>{c.name}</b></button>) : <p className="atelier-quiet">Your next beautiful project begins with a conversation.</p>}</div></section></div>
  </div>;
}

export function EventDirectory({ data, funeral, open, create }: { data: StudioData; funeral: boolean; open: (plan: WeddingPlan) => void; create: (type: WeddingPlan['type']) => void }) {
  const plans = data.plans.filter(p => funeral ? p.type === 'Funeral' : p.type !== 'Funeral').sort((a,b) => b.eventDate.localeCompare(a.eventDate));
  return <div className="studio-event-directory"><header className="ops-heading"><p className="eyebrow">{funeral ? 'FLOWERS TO REMEMBER' : 'FLOWERS FOR THEIR DAY'}</p><h1>{funeral ? 'Funerals' : 'Weddings & Events'}</h1><p>{funeral ? 'Thoughtful tributes, planned with care.' : 'From the first idea to the last stem in place.'}</p></header><div className="ops-toolbar"><button className="button" onClick={() => create(funeral ? 'Funeral' : 'Wedding')}>+ New {funeral ? 'Funeral' : 'Wedding'}</button>{!funeral && <button onClick={() => create('Corporate')}>+ New Event</button>}</div><div className="ops-record-grid">{plans.map(p => <button className="ops-record-card studio-event-card" key={p.id} onClick={() => open(p)}><Photo src={p.inspiration?.[0]?.image || p.references?.[0]?.dataUrl} alt={`${p.clientName} floral inspiration`} /><div><small>{p.type} · {p.status || 'Enquiry'}</small><h2>{p.clientName}</h2><p>{p.eventDate || 'Date to confirm'} · {p.venue || 'Venue to confirm'}</p><span>Open floral plan →</span></div></button>)}</div>{!plans.length && <section className="ops-panel studio-calm-empty">Start a new floral plan. We’ll guide you through each step.</section>}</div>;
}
