'use client';
import { useState, type ReactNode } from 'react';
import Dialog from '../dialog';
import { StudioBrand, StudioIcon, type IconName } from './design-system';

type Action = { label: string; icon: IconName; run: () => void };
type Props = { mode: 'business' | 'client'; tab: string; busy: boolean; saveState: string; onMode: (mode: 'business' | 'client') => void; navigate: (tab: string) => void; signOut: () => void; actions: Action[]; search: ReactNode; clientNavigation: ReactNode };
const primary: [string, string, IconName][] = [['dashboard','Home','home'],['calendar','Calendar','calendar'],['clients','Clients','clients'],['events','Events','events'],['calculator','Recipes','flower'],['inventory','Flowers','flower'],['jobs','Orders','orders'],['suppliers','Suppliers','suppliers'],['financial','Finance','finance']];
const secondary = [['funerals','Funeral plans'],['recurring','Routine flowers'],['catalogue','Inspiration catalogue'],['production','Production'],['deliveries','Deliveries & setup'],['hire','Hire items'],['payments','Payments'],['insights','Flower & waste insights'],['leads','Enquiries'],['tasks','Tasks'],['templates','Recipe library'],['assistant','AI assistant'],['activity','Activity history']];
export default function StudioNavigation({ mode, tab, busy, saveState, onMode, navigate, signOut, actions, search, clientNavigation }: Props) {
  const [menu, setMenu] = useState(false); const [creating, setCreating] = useState(false);
  const go = (section: string) => { navigate(section); setMenu(false); };
  const navigation = <><div className="atelier-sidebar-brand"><StudioBrand /><p>BUSINESS STUDIO</p></div><nav aria-label="Business workspace">{primary.map(([key,label,icon]) => <button key={key} type="button" disabled={busy} aria-current={tab === key ? 'page' : undefined} onClick={() => go(key)}><StudioIcon name={icon} />{label}</button>)}<details className="atelier-tools" open={secondary.some(([key]) => key === tab) || undefined}><summary><StudioIcon name="studio" />Studio <span>⌄</span></summary>{secondary.map(([key,label]) => <button type="button" key={key} disabled={busy} aria-current={tab === key ? 'page' : undefined} onClick={() => go(key)}>{label}</button>)}</details><div className="atelier-nav-secondary">{[['reports','Reports'],['settings','Settings']].map(([key,label]) => <button type="button" key={key} disabled={busy} aria-current={tab === key ? 'page' : undefined} onClick={() => go(key)}>{label}</button>)}</div></nav><div className="atelier-sidebar-footer"><p>Beautiful flowers.<br /><em>Brighter days.</em></p><a href="/">View website ↗</a><button type="button" disabled={busy} onClick={signOut}>Sign out</button></div></>;
  const modeSwitch = <div className="atelier-mode-switch" aria-label="Studio experience">{(['business','client'] as const).map(value => <button type="button" key={value} disabled={busy} aria-pressed={mode === value} onClick={() => onMode(value)}>{value === 'business' ? 'Business Studio' : 'Client Studio'}</button>)}</div>;
  return <>
    {mode === 'business' && <aside className="atelier-sidebar">{navigation}</aside>}
    <header className="atelier-topbar">{mode === 'client' && <a className="atelier-client-brand" href="/"><StudioBrand /></a>}{modeSwitch}{mode === 'business' && search}<div className="atelier-topbar-actions"><span className={`atelier-save ${saveState}`} role="status">{saveState === 'saving' ? 'Saving…' : saveState === 'error' ? 'Save needs attention' : saveState === 'saved' ? 'Saved' : 'Connecting…'}</span>{mode === 'business' && <button className="atelier-create button" disabled={busy} onClick={() => setCreating(true)}><StudioIcon name="plus" />Create</button>}<span className="atelier-avatar" title="Jade · Studio owner">J</span></div></header>
    {mode === 'client' && <div className="atelier-client-navigation">{clientNavigation}</div>}
    {mode === 'business' && <nav className="atelier-mobile-nav" aria-label="Mobile Studio navigation"><button disabled={busy} aria-current={tab === 'dashboard' ? 'page' : undefined} onClick={() => go('dashboard')}><StudioIcon name="home" />Home</button><button disabled={busy} aria-current={tab === 'calendar' ? 'page' : undefined} onClick={() => go('calendar')}><StudioIcon name="calendar" />Calendar</button><button disabled={busy} className="atelier-mobile-create" aria-label="Create something new" onClick={() => setCreating(true)}><StudioIcon name="plus" /></button><button disabled={busy} aria-current={tab === 'clients' ? 'page' : undefined} onClick={() => go('clients')}><StudioIcon name="clients" />Clients</button><button aria-expanded={menu} onClick={() => setMenu(true)}><StudioIcon name="studio" />More</button></nav>}
    {menu && <Dialog className="atelier-menu-dialog" label="Studio navigation" onClose={() => setMenu(false)}><button className="atelier-dialog-close" onClick={() => setMenu(false)}>Close ×</button>{navigation}</Dialog>}
    {creating && <Dialog className="atelier-create-dialog" label="Create something beautiful" onClose={() => setCreating(false)}><div className="atelier-section-heading"><h2>What’s next?</h2><button aria-label="Close quick actions" onClick={() => setCreating(false)}>×</button></div><p>A new idea, a new client, a little progress.</p><div className="atelier-create-grid">{actions.map(action => <button disabled={busy} key={action.label} onClick={() => { setCreating(false); action.run(); }}><StudioIcon name={action.icon} />{action.label}<span>→</span></button>)}</div></Dialog>}
  </>;
}

export function StudioGateway({ enter, signOut, saveState }: { enter: (mode: 'business' | 'client') => void; signOut: () => void; saveState: string }) {
  return <main className="atelier-gateway"><div className="atelier-gateway-photo" role="img" aria-label="Bramble & Petal pastel wedding flowers in the sunlight" /><section><StudioBrand /><p className="eyebrow">WELCOME TO YOUR STUDIO</p><h1>A place for<br /><em>beautiful beginnings.</em></h1><p>Two spaces. One thoughtful journey, from the first conversation to the final stem.</p><div className="atelier-space-choices"><button onClick={() => enter('business')}><StudioIcon name="studio" /><span><strong>Business Studio</strong><small>Your day, your flowers, your business.</small></span><StudioIcon name="arrow" /></button><button onClick={() => enter('client')}><StudioIcon name="flower" /><span><strong>Client Studio</strong><small>Plan something personal, together.</small></span><StudioIcon name="arrow" /></button></div><p className="atelier-gateway-status">{saveState === 'saved' ? 'Your Studio is up to date.' : 'Your records stay connected between both spaces.'}</p><div className="atelier-gateway-links"><a href="/">Back to website</a><button onClick={signOut}>Sign out</button></div></section></main>;
}
