'use client';
import { useEffect, useState } from 'react';
import type { clientEvent, clientQuotation } from '@/lib/client-portal';
import type { InspirationItem } from '@/lib/operations-types';
import { CatalogueBrowse } from '../studio/inspiration-catalogue';
import { Photo, Assets } from '../studio/ops-ui';
import { money } from '@/lib/pricing';
import { StudioBrand } from '../studio/design-system';
type Portal = { plan: ReturnType<typeof clientEvent>; quotes: ReturnType<typeof clientQuotation>[]; updatedAt: string };
export default function ClientPortal() {
  const [data, setData] = useState<Portal | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [section, setSection] = useState('Your plan');
  const [items, setItems] = useState<InspirationItem[]>([]); const [more, setMore] = useState(false); const [search, setSearch] = useState('');
  const [notes, setNotes] = useState(''); const [palette, setPalette] = useState(''); const [flowers, setFlowers] = useState(''); const [comments, setComments] = useState(''); const [accepted, setAccepted] = useState(false);
  const apply = (body: Portal) => { setData(body); setNotes(body.plan.notes); setPalette(body.plan.palette); setFlowers(body.plan.favouriteFlowers); };
  async function refresh() { const r = await fetch('/api/client'); const body = await r.json(); if (!r.ok) throw new Error(body.error); apply(body); }
  useEffect(() => { let active = true; async function load() { try { const invite = new URLSearchParams(location.hash.slice(1)).get('invite'); if (invite) { const r = await fetch('/api/client/session', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ invite }) }); const body = await r.json(); if (!r.ok) throw new Error(body.error); history.replaceState(null, '', '/client'); } if (active) await refresh(); } catch (e) { if (active) setError(e instanceof Error ? e.message : 'Your plan could not be loaded.'); } finally { if (active) setBusy(false); } } void load(); return () => { active = false; }; }, []);
  async function catalogue(offset = 0) { setBusy(true); setError(''); try { const r = await fetch(`/api/client/catalogue?offset=${offset}&q=${encodeURIComponent(search)}`); const body = await r.json(); if (!r.ok) throw new Error(body.error); setItems(previous => offset ? [...previous, ...body.items] : body.items); setMore(body.hasMore); } catch (e) { setError(e instanceof Error ? e.message : 'Inspiration could not be loaded.'); } finally { setBusy(false); } }
  async function change(body: Record<string, unknown>) { if (!data) return; setBusy(true); setError(''); setNotice(''); try { const r = await fetch('/api/client', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...body, expectedUpdatedAt: data.updatedAt }) }); const result = await r.json(); if (!r.ok) throw new Error(result.error); apply(result); setNotice('Your floral plan has been saved.'); } catch (e) { setError(e instanceof Error ? e.message : 'Your changes could not be saved.'); } finally { setBusy(false); } }
  const estimate = (data?.plan.inspiration || []).reduce((s, i) => ({ from: s.from + i.quantity * i.priceFrom, to: s.to + i.quantity * i.priceTo }), { from: 0, to: 0 });
  return <main className="client-portal atelier-client-portal"><header className="client-portal-header"><a href="/" className="client-portal-brand"><StudioBrand /><small>CLIENT STUDIO</small></a>{data && <button type="button" onClick={async () => { const r = await fetch('/api/client/session', { method: 'DELETE' }); if (r.ok) { setData(null); setNotice('Signed out. Open your private invitation to return.'); } }}>Sign out</button>}</header><div className="client-portal-content">{error && <div role="alert" className="ops-inline-notice"><p>{error}</p><button type="button" onClick={() => void refresh().catch(e => setError(e.message))}>Reload plan</button></div>}{notice && <p role="status">{notice}</p>}{!data ? <section className="ops-empty"><h1>{busy ? 'Opening your floral plan…' : 'Your private floral plan'}</h1><p>{!busy && 'Use the invitation supplied by Jade to view your event.'}</p></section> : <><header className="atelier-portal-welcome"><div><p className="eyebrow">YOUR PERSONAL CLIENT STUDIO</p><h1>{data.plan.clientName}</h1><p>{data.plan.type === 'Funeral' ? 'Thoughtful flowers, in remembrance.' : data.plan.type === 'Corporate' ? 'Flowers that belong in your space.' : 'Your day. Your flowers. Your story.'}</p><small>{data.plan.eventDate || 'Date to confirm'} · {data.plan.venue || 'Venue to confirm'}</small></div><Photo src={data.plan.inspiration[0]?.image || (data.plan.type === 'Funeral' ? '/assets/sympathy-spray.jpg' : '/assets/weddings/pastel-pedestal-details.webp')} alt="Floral inspiration for your consultation" /></header><nav className="ops-section-tabs" aria-label="Your floral plan">{['Your plan', 'Inspiration', 'Your preferences', 'Quotation'].map(s => <button type="button" disabled={busy} key={s} aria-current={section === s ? 'page' : undefined} onClick={() => { setSection(s); if (s === 'Inspiration') void catalogue(); }}>{s}</button>)}</nav><fieldset disabled={busy}>
    {section === 'Your plan' && <><section className="ops-panel"><h2>Your floral direction</h2><p>{data.plan.palette || 'Choose your colours together with Jade.'}</p><p>{data.plan.favouriteFlowers}</p><p>{data.plan.arrangements}</p>{data.plan.inspiration.length > 0 && <div className="ops-total"><span>Inspiration guide estimate</span><strong>{money(estimate.from)}–{money(estimate.to)}</strong><p>Guide prices only. Your formal quotation confirms the final designs, availability, setup and delivery.</p></div>}</section><div className="ops-record-grid">{data.plan.inspiration.map(i => <article className="ops-panel" key={i.id}><Photo src={i.image} alt={i.name} /><h2>{i.name}</h2><p>{i.quantity} required · {money(i.priceFrom * i.quantity)}–{money(i.priceTo * i.quantity)}</p><p>{i.description}</p><p>{i.notes}</p><button type="button" onClick={() => void change({ action: 'removeInspiration', selectionId: i.id })}>Remove idea</button></article>)}</div>{data.plan.requirements.length > 0 && <section className="ops-panel"><h2>Your arrangement list</h2>{data.plan.requirements.map(r => <p key={r.id}>{r.quantity} × {r.name} · {r.notes}</p>)}</section>}{data.plan.setupOptions.length > 0 && <section className="ops-panel"><h2>Setup options</h2>{data.plan.setupOptions.map(o => <article key={o.id}><Photo src={o.photoSrc} alt={o.title} /><h3>{o.title}</h3><p>{o.description}</p><p>{o.quantity} × {o.unitPrice === null ? 'Price to confirm' : money(o.unitPrice)}</p></article>)}</section>}<div className="ops-asset-list">{data.plan.references.map(r => <figure key={r.id}><Photo src={r.dataUrl} alt={r.name} /><figcaption>{r.caption || r.name}</figcaption></figure>)}</div><button type="button" onClick={() => window.print()}>Print your floral plan</button></>}
    {section === 'Inspiration' && <><h2>Find something you love</h2><form className="ops-toolbar" onSubmit={e => { e.preventDefault(); void catalogue(); }}><label>Search the full catalogue<input value={search} onChange={e => setSearch(e.target.value)} /></label><button type="submit">Search</button></form><CatalogueBrowse items={items} occasion={data.plan.type} onSelect={(item, quantity) => void change({ action: 'inspiration', inspirationId: item.id, quantity })} />{more && <button type="button" onClick={() => void catalogue(items.length)}>Load more inspiration</button>}</>}
    {section === 'Your preferences' && <section className="ops-panel"><h2>Make it yours</h2><form onSubmit={e => { e.preventDefault(); void change({ action: 'notes', notes, palette, flowers }); }}><div className="ops-fields"><label>Colours you love<input value={palette} onChange={e => setPalette(e.target.value)} /></label><label>Favourite flowers<input value={flowers} onChange={e => setFlowers(e.target.value)} /></label><label className="ops-wide">Your notes for Jade<textarea rows={5} maxLength={10000} value={notes} onChange={e => setNotes(e.target.value)} /></label></div><button type="submit" className="button">Save preferences</button></form><h3>Your inspiration photographs</h3><Assets imagesOnly removable={false} max={20} value={data.plan.references.map(r => ({ id: r.id, name: r.name, url: r.dataUrl, type: 'image/jpeg' }))} onChange={() => void refresh().catch(e => setError(e.message))} label="Upload an inspiration photograph" /><p>Uploads are saved to your private plan for Jade to review.</p></section>}
    {section === 'Quotation' && <>{data.quotes.length ? data.quotes.map(q => <section className="ops-panel client-quotation" key={q.id}><p className="eyebrow">{q.status === 'PURCHASED' ? 'CONFIRMED ORDER' : 'YOUR FORMAL QUOTATION'}</p><h2>{q.name}</h2>{q.recipes.map(r => <div className="ops-rank" key={r.id}><span>{r.quantity} × {r.name}</span><b>{money(r.total)}</b></div>)}<p>Setup: {money(q.setupGross)} · Delivery: {money(q.deliveryGross)} · Hire: {money(q.hireGross)} · Discount: {money(q.discountGross)} (including applicable VAT)</p><div className="ops-total"><span>Total, including {money(q.vat)} VAT</span><strong>{money(q.total)}</strong></div><p>Payments recorded: {money(q.paid)} · Balance: {money(q.balance)}</p><p>Payment due: {q.paymentDue || 'To be arranged'}{q.depositDue > 0 && ` · Deposit: ${money(q.depositDue)}`}</p>{q.stages.map(s => <p key={s.id}>{s.name} · {money(s.amount)} · {s.due}</p>)}<h3>Terms</h3><p style={{ whiteSpace: 'pre-wrap' }}>{q.terms || 'Please discuss the booking terms with Jade.'}</p>{q.approval && <p>Response: {q.approval.status} · {q.approval.comments}</p>}{q.status === 'QUOTE' && <><label className="ops-block-label">Comments or requested changes<textarea value={comments} onChange={e => setComments(e.target.value)} maxLength={5000} /></label><label className="ops-check"><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} />I accept the quotation and its terms.</label><div className="ops-toolbar"><button type="button" className="button" disabled={!accepted} onClick={() => void change({ action: 'approval', quoteId: q.id, status: 'Approved', comments, termsAccepted: accepted })}>Approve quotation</button><button type="button" onClick={() => void change({ action: 'approval', quoteId: q.id, status: 'Changes requested', comments, termsAccepted: false })}>Request changes</button></div><p>Your response is sent to the Studio. This does not take payment.</p></>}<button type="button" onClick={() => window.print()}>Print quotation</button></section>) : <section className="ops-empty"><h2>Your quotation is being prepared</h2><p>Jade will add your formal quotation after reviewing your floral plans.</p></section>}</>}
  </fieldset></>}</div></main>;
}
