 'use client';
import { useCallback, useEffect, useState, type FormEvent, type MouseEvent } from 'react';
import ClampedText from '../../public/clamped-text';
type Review={id:string;client_label:string;expires_at:string;revoked_at:string|null;public_name:string|null;review_text:string|null;rating:number|null;submitted_at:string|null;published:boolean;highlight:string|null};
export default function ReviewManager(){
 const [items,setItems]=useState<Review[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[link,setLink]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{const response=await fetch('/api/studio/reviews',{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error);setItems(result.reviews);},[]);
 useEffect(()=>{load().catch(error=>setError(error.message)).finally(()=>setLoading(false));},[load]);
 async function action(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/studio/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error);if(result.invite)setLink(`${window.location.origin}/review#${result.invite}`);else setNotice('Saved. The website will reflect this change on its next load.');await load();}catch(error){setError(error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}}
 function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();action({action:'invite',label:new FormData(event.currentTarget).get('label')});}
 async function copy(){try{await navigator.clipboard.writeText(link);setNotice('Review link copied. You can now send it to your client.');}catch{setNotice('Select and copy the link below.');}}
 return <><form className="bp-enquiry-form public-review-invite" onSubmit={invite}><div className="bp-field"><label htmlFor="client-label">Client reference (private)</label><input id="client-label" name="label" required maxLength={120} placeholder="Client or event name"/></div><button type="submit" disabled={busy}>Create review link</button><p>Single use · expires after 90 days · no email sent automatically</p></form>{link&&<section className="public-created-link"><h2>Your invitation is ready.</h2><p>Copy this link now; the secure link is only shown when it is created.</p><label htmlFor="review-link">Client review link</label><input id="review-link" readOnly value={link} onFocus={event=>event.currentTarget.select()}/><button className="public-button" onClick={copy}>Copy link</button></section>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<h2>Reviews &amp; invitations</h2>{loading?<p>Loading…</p>:!items.length?<p>No invitations yet.</p>:<div className="public-review-admin-list">{items.map(item=><article key={item.id}><div><h3>{item.client_label}</h3><p>{item.submitted_at?(item.published?'Published':'Waiting for your approval'):item.revoked_at?'Invitation withdrawn':new Date(item.expires_at)<new Date()?'Invitation expired':'Awaiting review'}</p></div>{item.submitted_at?<><p>{item.rating} / 5 · {item.public_name}</p><ClampedText text={item.review_text??''} lines={3} buttonClassName="public-text-link" moreLabel="Show full review"/><HighlightEditor review={item} busy={busy} onSave={highlight=>action({action:'highlight',id:item.id,highlight})}/><button className="public-button" disabled={busy} onClick={()=>action({action:'visibility',id:item.id,published:!item.published})}>{item.published?'Hide from website':'Publish on website'}</button></>:!item.revoked_at&&<button className="public-text-link" disabled={busy} onClick={()=>action({action:'revoke',id:item.id})}>Withdraw invitation</button>}</article>)}</div>}</>;
}
// Jade picks a passage from the review to show in large type on the website.
function HighlightEditor({review,busy,onSave}:{review:Review;busy:boolean;onSave:(highlight:string|null)=>void}){
 const [draft,setDraft]=useState(review.highlight??''),[hint,setHint]=useState('');
 useEffect(()=>setDraft(review.highlight??''),[review.highlight]);
 function pickSelection(event:MouseEvent<HTMLButtonElement>){const quote=event.currentTarget.closest('article')?.querySelector('blockquote'),selection=window.getSelection(),text=selection?.toString().trim()??'';if(!quote||!text||!selection?.anchorNode||!quote.contains(selection.anchorNode)||!quote.contains(selection.focusNode)){setHint('Select some words in the review above first. Open the full review to select from the whole text.');return;}setDraft(text.replace(/\s+/g,' '));setHint('');}
 const id=`highlight-${review.id}`,changed=draft.trim()!==(review.highlight??'');
 return <div className="public-review-highlight-editor"><label htmlFor={id}>Website highlight <small>(optional · shown large at the top of the review card)</small></label><textarea id={id} rows={2} maxLength={280} value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Select a passage in the review, then choose “Use selected text”"/>{hint&&<p role="status">{hint}</p>}<div><button type="button" className="public-text-link" onMouseDown={event=>event.preventDefault()} onClick={pickSelection}>Use selected text</button><button type="button" className="public-text-link" disabled={busy||!changed||!draft.trim()} onClick={()=>onSave(draft)}>Save highlight</button>{review.highlight&&<button type="button" className="public-text-link" disabled={busy} onClick={()=>onSave(null)}>Remove highlight</button>}</div></div>;
}
