 'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
type Review={id:string;client_label:string;expires_at:string;revoked_at:string|null;public_name:string|null;review_text:string|null;rating:number|null;submitted_at:string|null;published:boolean};
export default function ReviewManager(){
 const [items,setItems]=useState<Review[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[link,setLink]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{const response=await fetch('/api/studio/reviews',{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error);setItems(result.reviews);},[]);
 useEffect(()=>{load().catch(error=>setError(error.message)).finally(()=>setLoading(false));},[load]);
 async function action(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/studio/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error);if(result.invite)setLink(`${window.location.origin}/review#${result.invite}`);else setNotice('Saved. The website will reflect this change on its next load.');await load();}catch(error){setError(error instanceof Error?error.message:'Please try again.');}finally{setBusy(false);}}
 function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();action({action:'invite',label:new FormData(event.currentTarget).get('label')});}
 async function copy(){try{await navigator.clipboard.writeText(link);setNotice('Review link copied. You can now send it to your client.');}catch{setNotice('Select and copy the link below.');}}
 return <><form className="bp-enquiry-form public-review-invite" onSubmit={invite}><div className="bp-field"><label htmlFor="client-label">Client reference (private)</label><input id="client-label" name="label" required maxLength={120} placeholder="Client or event name"/></div><button type="submit" disabled={busy}>Create review link</button><p>Single use · expires after 90 days · no email sent automatically</p></form>{link&&<section className="public-created-link"><h2>Your invitation is ready.</h2><p>Copy this link now; the secure link is only shown when it is created.</p><label htmlFor="review-link">Client review link</label><input id="review-link" readOnly value={link} onFocus={event=>event.currentTarget.select()}/><button className="public-button" onClick={copy}>Copy link</button></section>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<h2>Reviews &amp; invitations</h2>{loading?<p>Loading…</p>:!items.length?<p>No invitations yet.</p>:<div className="public-review-admin-list">{items.map(item=><article key={item.id}><div><h3>{item.client_label}</h3><p>{item.submitted_at?(item.published?'Published':'Waiting for your approval'):item.revoked_at?'Invitation withdrawn':new Date(item.expires_at)<new Date()?'Invitation expired':'Awaiting review'}</p></div>{item.submitted_at?<><p>{item.rating} / 5 · {item.public_name}</p><blockquote>{item.review_text}</blockquote><button className="public-button" disabled={busy} onClick={()=>action({action:'visibility',id:item.id,published:!item.published})}>{item.published?'Hide from website':'Publish on website'}</button></>:!item.revoked_at&&<button className="public-text-link" disabled={busy} onClick={()=>action({action:'revoke',id:item.id})}>Withdraw invitation</button>}</article>)}</div>}</>;
}
