import { pageMetadata, PHONE_DISPLAY, PHONE_E164 } from '@/lib/site-seo';
import Image from 'next/image';
import ClientReviews from './public/reviews';
import { loadPublishedReviews } from '@/lib/public-reviews';
import Link from 'next/link';
import EnquiryForm from './enquiry-form';
import { PublicPage, Intro, PhotoFrame, TextLink, ConsultationCTA, Arrow } from './public/components';

export const metadata = pageMetadata('/');
// Re-render at most every five minutes so newly published reviews reach the page HTML.
export const revalidate = 300;

export default async function Home() {
  const reviews = await loadPublishedReviews();
  return <PublicPage className="public-home">
    <section className="public-hero" aria-labelledby="home-title"><div className="public-hero-copy"><h1 id="home-title"><span className="public-kicker">SOUTHAMPTON &amp; NEW FOREST FLORIST</span>Flowers for life’s<br /><em>most beautiful</em><br />moments.</h1><p>Your Southampton florist for weddings, farewells<br className="public-desktop-break" /> and the moments in between.</p><Link className="public-button" href="#weddings">Discover our work<Arrow /></Link><span className="public-hero-signature">Beautiful flowers. Brighter days.</span></div><div className="public-hero-image"><Image src="/assets/weddings/wedding-hero-wide.webp" alt="A wedding couple surrounded by pastel floral arrangements in a light-filled ceremony room" fill sizes="100vw" unoptimized preload /></div></section>
    <section className="public-welcome public-split" id="about"><div className="public-section-copy"><Intro label="WELCOME TO BRAMBLE & PETAL" title={<>Thoughtful flowers,<br />for every occasion.</>}>Inspired by the season and the people they’re made for. From a wedding day to a heartfelt goodbye, we create flowers with care, character and a personal touch.</Intro><TextLink href="/our-studio">Our story</TextLink></div><PhotoFrame src="/assets/weddings/pastel-pedestal-details.webp" alt="Cream roses, white dahlias, lilac flowers and green hydrangeas arranged by Bramble & Petal" /><span className="public-side-note">Seasonal flowers.<br />Expertly arranged.</span></section>
    <section className="public-services public-wrap" id="services" aria-label="Flowers for every occasion"><div className="public-service-grid"><Link href="/weddings" className="public-service"><PhotoFrame src="/assets/weddings/bridal-party-bouquets.webp" alt="Bride and bridesmaid with coordinating pale blue and white bouquets" sizes="(max-width: 700px) 50vw, 25vw" position="50% 66%" /><div><h2>Weddings</h2><span>Your day, in flowers. <Arrow /></span></div></Link><Link href="/funerals" className="public-service"><PhotoFrame src="/assets/sympathy-spray.jpg" alt="A white and green floral spray made in the Bramble & Petal studio" sizes="(max-width: 700px) 50vw, 25vw" /><div><h2>Funerals</h2><span>Made with care. <Arrow /></span></div></Link><Link href="/corporate" className="public-service public-service-type"><span className="public-placeholder-line" aria-hidden="true">B &amp; P</span><p>For spaces.<br />For gatherings.<br /><em>For your business.</em></p><div><h2>Corporate</h2><span>Considered floral design. <Arrow /></span></div></Link><Link href="/flowers" className="public-service"><PhotoFrame src="/assets/studio-work-2.jpg" alt="A hand-tied white bouquet with green eucalyptus, ready in the studio" sizes="(max-width: 700px) 50vw, 25vw" /><div><h2>Everyday flowers</h2><span>A little joy, delivered. <Arrow /></span></div></Link></div></section>
    <section className="public-wedding-story public-wrap" id="weddings"><div className="public-story-heading"><Intro label="THE WEDDING COLLECTION" title={<>Entirely yours.<br /><em>From the first stem.</em></>}>Your venue, your season, your way of celebrating. Flowers that bring it all together.</Intro><TextLink href="/weddings">Explore weddings</TextLink></div><div className="public-wedding-mosaic"><PhotoFrame className="public-mosaic-main" src="/assets/weddings/wedding-02.jpg" alt="Two pastel pedestal arrangements framing the ceremony table beneath a grand arched window" sizes="(max-width: 700px) 100vw, 55vw" /><PhotoFrame className="public-mosaic-detail" src="/assets/weddings/sunlit-ceremony-flowers.webp" alt="Sunlit white, lilac and green flowers from the same ceremony design" sizes="(max-width: 700px) 50vw, 29vw" /><PhotoFrame className="public-mosaic-personal" src="/assets/weddings/flower-girl-crown.webp" alt="A flower girl wearing a delicate white flower crown and carrying a petal basket" sizes="(max-width: 700px) 50vw, 24vw" /></div></section>
    <ClientReviews initialReviews={reviews} />
    <section className="public-studio-story public-split" id="studio"><div className="public-process-photos"><PhotoFrame src="/assets/weddings/creating-wedding-flowers.webp" alt="A florist creating a pastel wedding arrangement by hand in the studio" sizes="(max-width: 700px) 75vw, 38vw" /><PhotoFrame src="/assets/weddings/pastel-flowers-arriving.webp" alt="A woman carrying freshly gathered pale blue and white flowers in the sunshine" sizes="(max-width: 700px) 45vw, 22vw" /></div><div className="public-section-copy"><Intro label="INSIDE OUR STUDIO" title={<>From our hands,<br /><em>to your moments.</em></>}>A conversation, a gathering of ideas, then the making. We consider each stem, from the first design to the final flowers in place.</Intro><TextLink href="/our-studio">Meet the studio</TextLink></div></section>
    <section className="public-client-section" id="client-studio"><div className="public-client-frame" aria-label="Client Studio introduction"><div className="public-browser-bar"><span /><span /><span /><small>BRAMBLE &amp; PETAL · CLIENT STUDIO</small></div><div className="public-client-preview"><Image src="/assets/brand-logo.png" width={160} height={110} alt="Bramble & Petal Florist Studio" /><p className="public-kicker">A SPACE FOR YOUR IDEAS</p><h3>Your flowers.<br /><em>Your story.</em></h3><p>Colours · Inspiration · Your floral plan</p><Link href="/client">Open your private invitation <Arrow /></Link><small>For clients with an invitation from the studio.</small></div></div><div className="public-section-copy"><Intro label="PLAN SOMETHING PERSONAL" title={<>Introducing the<br />Bramble &amp; Petal<br /><em>Client Studio.</em></>}>A space to gather inspiration, explore your flowers and review your plan together. Begin with a consultation; we’ll arrange your private invitation.</Intro><ul className="public-client-features"><li>Weddings</li><li>Funeral flowers</li><li>Corporate events</li><li>Regular flowers</li></ul><ConsultationCTA /></div></section>
    <section className="public-sympathy public-split" id="sympathy"><div className="public-section-copy"><Intro label="FLOWERS IN REMEMBRANCE" title={<>Flowers created<br /><em>with care.</em></>}>Thoughtful tributes that reflect the person being remembered and the wishes of those closest to them.</Intro><TextLink href="/funerals">Funeral flowers</TextLink></div><PhotoFrame src="/assets/sympathy-tribute.jpg" alt="Bramble & Petal floral tributes with white lettering and arrangements prepared for a farewell" position="center" /></section>
    <section className="public-business-flowers public-wrap" id="corporate"><div><Intro label="FOR YOUR BUSINESS" title={<>A fresh perspective.<br /><em>Week after week.</em></>}>Flowers for welcoming spaces, memorable events and regular moments of renewal.</Intro><TextLink href="/corporate">Corporate flowers</TextLink></div><div className="public-business-list"><p>Offices &amp; reception spaces</p><p>Restaurants &amp; hospitality</p><p>Events &amp; gatherings</p><p>Regular floral arrangements</p><TextLink href="/flowers">Explore regular flowers</TextLink></div></section>
    <section className="public-detail-section" id="work" aria-label="A closer look at our flowers"><div className="public-detail-title"><p className="public-kicker">A CLOSER LOOK</p><h2>Nature, beautifully considered.</h2></div><div className="public-detail-strip"><PhotoFrame src="/assets/studio-work-4.jpg" alt="Pale yellow and lilac flowers gathered on the studio workbench" sizes="(max-width: 700px) 50vw, 25vw" /><PhotoFrame src="/assets/weddings/pastel-pedestal-details.webp" alt="A close look at cream roses and lilac wedding flowers" sizes="(max-width: 700px) 50vw, 25vw" /><PhotoFrame src="/assets/studio-consultations.jpg" alt="The wooden Bramble & Petal consultation studio" sizes="(max-width: 700px) 50vw, 25vw" /><PhotoFrame src="/assets/bouquet-04.jpg" alt="A hand-tied bouquet of peach, cream and blush roses" sizes="(max-width: 700px) 50vw, 25vw" /></div></section>
    <section className="public-enquire public-wrap" id="enquire"><div><Intro label="LET’S BEGIN" title={<>Tell us what<br />you’re planning.</>}>A date, a place, a favourite flower. Share what you know; we’ll explore the rest together.</Intro><a className="public-email" href="mailto:info@bramblesandpetals.co.uk">info@bramblesandpetals.co.uk</a><br /><a className="public-email" href={`tel:${PHONE_E164}`}>{PHONE_DISPLAY}</a></div><EnquiryForm /></section>
  </PublicPage>;
}
