export type StudioTheme = {id:string;name:string;category:'Botanical'|'Editorial'|'Modern'|'Dark';description:string;bg:string;surface:string;ink:string;muted:string;accent:string;onAccent:string;soft:string;nav:string;navInk:string;radius:number;font:string;layout:'classic'|'topbar'|'rail'|'editorial'|'soft'};
const serif="Georgia, 'Times New Roman', serif",sans="Arial, Helvetica, sans-serif",mono="'Courier New', monospace";
export const themes:StudioTheme[]=[
{id:'bramble',name:'Bramble',category:'Botanical',description:'The original. Plum, paper and a little wild charm.',bg:'#f5f0ec',surface:'#fffdf8',ink:'#422b3c',muted:'#7a6774',accent:'#61415a',onAccent:'#fffaf6',soft:'#ecdee6',nav:'#493141',navInk:'#fff8f0',radius:12,font:serif,layout:'classic'},
{id:'glasshouse',name:'Glasshouse',category:'Botanical',description:'Lush green, open spaces and a fresh perspective.',bg:'#eef3ee',surface:'#ffffff',ink:'#193f32',muted:'#526d61',accent:'#286448',onAccent:'#ffffff',soft:'#dcebdc',nav:'#ffffff',navInk:'#193f32',radius:16,font:sans,layout:'topbar'},
{id:'petal',name:'Petal',category:'Botanical',description:'Soft rose, rounded edges and an easy rhythm.',bg:'#fcf0f2',surface:'#fffafb',ink:'#603245',muted:'#856672',accent:'#99516d',onAccent:'#ffffff',soft:'#f6dbe4',nav:'#f5dce4',navInk:'#603245',radius:24,font:serif,layout:'soft'},
{id:'atelier',name:'Atelier',category:'Editorial',description:'Fashion-house restraint. Ink, ivory and fine lines.',bg:'#f5f2ec',surface:'#fffdf9',ink:'#23201f',muted:'#746d64',accent:'#272320',onAccent:'#fffdf9',soft:'#e8e1d5',nav:'#f5f2ec',navInk:'#23201f',radius:0,font:serif,layout:'editorial'},
{id:'wildflower',name:'Wildflower',category:'Botanical',description:'Meadow yellow and generous, free-spirited shapes.',bg:'#f8f6e7',surface:'#fffef7',ink:'#494b27',muted:'#73764f',accent:'#5b6330',onAccent:'#ffffff',soft:'#ecebb6',nav:'#e9e8b2',navInk:'#494b27',radius:20,font:serif,layout:'soft'},
{id:'nocturne',name:'Nocturne',category:'Dark',description:'An after-hours studio with luminous lilac details.',bg:'#1d1b27',surface:'#2b2839',ink:'#f2eef9',muted:'#b6aec9',accent:'#cab2ed',onAccent:'#292035',soft:'#3c324d',nav:'#15131d',navInk:'#e0d7ed',radius:12,font:sans,layout:'rail'},
{id:'terracotta',name:'Terracotta',category:'Botanical',description:'Earthy clay, sculptural shapes and warm character.',bg:'#f5e9df',surface:'#fff6ed',ink:'#5c3528',muted:'#856354',accent:'#a55237',onAccent:'#fffaf3',soft:'#ebcabb',nav:'#8d4a35',navInk:'#fff4e5',radius:4,font:serif,layout:'classic'},
{id:'cobalt',name:'Cobalt',category:'Modern',description:'A bold blue workspace with a crisp, graphic edge.',bg:'#eef1fa',surface:'#ffffff',ink:'#17336e',muted:'#5e6d92',accent:'#2556c3',onAccent:'#ffffff',soft:'#dae4ff',nav:'#214bb0',navInk:'#ffffff',radius:8,font:sans,layout:'rail'},
{id:'linen',name:'Linen',category:'Editorial',description:'Quietly refined. Airy, tactile and beautifully simple.',bg:'#f4f1ea',surface:'#fffcf5',ink:'#504739',muted:'#817766',accent:'#776347',onAccent:'#fffdf5',soft:'#e7dfd0',nav:'#f4f1ea',navInk:'#504739',radius:3,font:serif,layout:'topbar'},
{id:'orchid',name:'Orchid',category:'Modern',description:'Expressive violet meets a playful modular layout.',bg:'#f2edf9',surface:'#fffcff',ink:'#502d74',muted:'#836597',accent:'#8149b4',onAccent:'#ffffff',soft:'#e8d8f6',nav:'#e7d7f4',navInk:'#502d74',radius:20,font:sans,layout:'soft'},
{id:'evergreen',name:'Evergreen',category:'Dark',description:'Deep forest, brass accents and considered luxury.',bg:'#132a25',surface:'#203b34',ink:'#f0efda',muted:'#b0bfb0',accent:'#d6c682',onAccent:'#26372d',soft:'#3d4b33',nav:'#10201c',navInk:'#e1e7d4',radius:4,font:serif,layout:'classic'},
{id:'cherry',name:'Cherry',category:'Modern',description:'Confident colour and a compact, energetic workspace.',bg:'#fff0ef',surface:'#fffaf8',ink:'#662f36',muted:'#936a6e',accent:'#ba3e50',onAccent:'#ffffff',soft:'#fbd7d9',nav:'#fff0ef',navInk:'#662f36',radius:8,font:sans,layout:'topbar'},
{id:'monograph',name:'Monograph',category:'Editorial',description:'A precise studio ledger for lovers of clean type.',bg:'#f1f1ee',surface:'#ffffff',ink:'#252526',muted:'#707073',accent:'#303033',onAccent:'#ffffff',soft:'#e2e2dc',nav:'#252526',navInk:'#f5f5ee',radius:0,font:mono,layout:'rail'},
{id:'coastal',name:'Coastal',category:'Modern',description:'Sea-glass blue and a calm, spacious horizon.',bg:'#eaf3f4',surface:'#fcffff',ink:'#245361',muted:'#5c7c85',accent:'#327e8c',onAccent:'#ffffff',soft:'#cfe9e9',nav:'#d8eded',navInk:'#245361',radius:15,font:sans,layout:'topbar'},
{id:'golden-hour',name:'Golden Hour',category:'Editorial',description:'Honey, espresso and the warmth of late afternoon.',bg:'#faf0d9',surface:'#fff9ea',ink:'#58421d',muted:'#88734e',accent:'#846018',onAccent:'#fff9e9',soft:'#eddb9e',nav:'#5d451e',navInk:'#fff5da',radius:6,font:serif,layout:'editorial'}
];
export function themeStyle(t:StudioTheme):Record<string,string>{return {'--demo-bg':t.bg,'--demo-surface':t.surface,'--demo-ink':t.ink,'--demo-muted':t.muted,'--demo-accent':t.accent,'--demo-on-accent':t.onAccent,'--demo-soft':t.soft,'--demo-nav':t.nav,'--demo-nav-ink':t.navInk,'--demo-radius':`${t.radius}px`,'--demo-font':t.font};}
export const getTheme=(id:string)=>themes.find(t=>t.id===id)??themes[0];
