import type { Metadata } from 'next';
import Link from 'next/link';
import { PublicPage, PhotoFrame, TextLink } from '../public/components';
export const metadata: Metadata = { title: 'Your Client Studio', description: 'Begin a flower consultation with Bramble & Petal, or return to your private floral proposal.', alternates: {canonical:'/client-studio'} };
const occasions = [{name:'Your wedding',value:'Wedding',text:'The day, the colours and the details that feel like you.'},{name:'A personal tribute',value:'Funeral flowers',text:'Thoughtful flowers and practical guidance, at your pace.'},{name:'Your business',value:'Corporate event',text:'Spaces, gatherings and flowers that work with your brand.'},{name:'Regular flowers',value:'Everyday flowers',text:'Seasonal arrangements for home, work or someone special.'}];
export default async function Page({searchParams}:{searchParams:Promise<{occasion?:string}>}) {
 const params = await searchParams; const selected = occasions.find(item=>item.value===params.occasion);
 return <PublicPage><section className="public-service-hero"><div className="public-section-copy"><p className="public-kicker">THE BRAMBLE & PETAL CLIENT STUDIO</p><h1>Your flowers.<br/><em>Your story.</em></h1><p className="public-copy">One conversation, one shared plan. Tell us what you’re imagining; your ideas stay with the studio as we shape your flowers together.</p><TextLink href="/client">Already invited? Open your plan</TextLink></div><PhotoFrame src="/assets/weddings/pastel-pedestal-details.webp" alt="Cream and lilac wedding flowers created by Bramble & Petal"/></section><section className="public-wrap public-consultation-options"><p className="public-kicker">START WITH YOUR OCCASION</p><h2>What are you planning?</h2><p className="public-copy">Begin with a consultation enquiry. We’ll be in touch to discuss your ideas and arrange a private Client Studio invitation when your plan is ready.</p><div className="public-occasion-grid">{occasions.map((item,index)=><Link key={item.value} className={selected?.value===item.value?'selected':''} href={`/contact?occasion=${encodeURIComponent(item.value)}`}><span>0{index+1}</span><h3>{item.name}</h3><p>{item.text}</p><strong>Begin your consultation →</strong></Link>)}</div></section><section className="public-wrap public-client-steps"><div><p className="public-kicker">01 · SHARE</p><h3>Bring your ideas.</h3><p>Your date, place, colours and priorities go straight to the studio.</p></div><div><p className="public-kicker">02 · SHAPE</p><h3>Explore the plan.</h3><p>We discuss your flowers and prepare a proposal around your brief.</p></div><div><p className="public-kicker">03 · REVIEW</p><h3>Your private invitation.</h3><p>Review the details and share feedback in your Client Studio, using the invitation we send you.</p></div></section></PublicPage>;
}
